import type { Enemy } from '../types'
import { et } from './loot'

export const z3: Record<string, Enemy> = {
  golemBaby: {
    id: 'golemBaby',
    spineAssetKey: 'golem_baby',
    damageType: 'physical',
    baseHp: 6.75,
    hpGrowth: 1.48,
    baseDamage: 12.5,
    damageGrowth: 1.38,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
  },
  slimeKnight: {
    id: 'slimeKnight',
    spineAssetKey: 'slime_knight',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.55,
    baseDamage: 15,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.31,
    speed: 11,
    crit: 0.03,
    dodge: 0,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime', 'armed'],
  },
  slimeBigMouth: {
    id: 'slimeBigMouth',
    spineAssetKey: 'slime_bigMouth',
    damageType: 'physical',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 16.26,
    damageGrowth: 1.38,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 11,
    crit: 0,
    dodge: 0,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime', 'blue'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  slimeCat: {
    id: 'slimeCat',
    spineAssetKey: 'slime_cat',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.48,
    baseDamage: 16.26,
    damageGrowth: 1.38,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 12,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime'],
  },
  slimeGems: {
    id: 'slimeGems',
    spineAssetKey: 'slime_gems',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 1.38,
    baseDefense: 7.5,
    defenseGrowth: 1.31,
    speed: 7,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime', 'armed'],
  },
  skeleton: {
    id: 'skeleton',
    spineAssetKey: 'skeleton',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.48,
    baseDamage: 13.76,
    damageGrowth: 1.38,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 10,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  skelNoHead: {
    id: 'skelNoHead',
    spineAssetKey: 'skel_noHead',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton'],
  },
  golemMountain: {
    id: 'golemMountain',
    spineAssetKey: 'golem_mountain',
    damageType: 'physical',
    baseHp: 13.05,
    hpGrowth: 2.03,
    baseDamage: 31.26,
    damageGrowth: 1.69,
    baseDefense: 7.5,
    defenseGrowth: 1.56,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem', 'armed'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  golemMountainLucky: {
    id: 'golemMountainLucky',
    spineAssetKey: 'golem_mountain',
    damageType: 'physical',
    baseHp: 13.05,
    hpGrowth: 2.03,
    baseDamage: 31.26,
    damageGrowth: 1.69,
    baseDefense: 7.5,
    defenseGrowth: 1.56,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLuckyLoot],
    tags: ['golem', 'armed'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  golemBoar: {
    id: 'golemBoar',
    spineAssetKey: 'golem_boar',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 1.44,
    baseDefense: 6,
    defenseGrowth: 1.37,
    speed: 9,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
  },
  skelFireHead: {
    id: 'skelFireHead',
    spineAssetKey: 'skel_fireHead',
    damageType: 'fire',
    baseHp: 22.5,
    hpGrowth: 7.43,
    baseDamage: 15,
    damageGrowth: 1,
    baseDefense: 3.75,
    defenseGrowth: 5.31,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.6,
    iceResist: -0.3,
    lightningResist: -0.3,
    shadowResist: -0.3,
    lootTables: [et.fireHeadBossLoot],
    abilities: [{ id: 'BossBrain_SkeletonFireHead' }],
    tags: ['boss', 'skeleton', 'red'],
  },
  skelIceHead: {
    id: 'skelIceHead',
    spineAssetKey: 'skel_iceHead',
    damageType: 'ice',
    baseHp: 45,
    hpGrowth: 7.43,
    baseDamage: 25,
    damageGrowth: 1.13,
    baseDefense: 11.25,
    defenseGrowth: 4.69,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: -0.3,
    iceResist: 0.6,
    lightningResist: -0.3,
    shadowResist: -0.3,
    lootTables: [et.fireHeadBossLoot],
    abilities: [{ id: 'BossBrain_SkeletonIceHead' }],
    tags: ['boss', 'skeleton', 'blue'],
  },
  skelArcher: {
    id: 'skelArcher',
    spineAssetKey: 'skel_archer',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.48,
    baseDamage: 15,
    damageGrowth: 1.44,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 12,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  skel2Axe: {
    id: 'skel2Axe',
    spineAssetKey: 'skel_2Axe',
    damageType: 'physical',
    baseHp: 15.3,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  slimeBone: {
    id: 'slimeBone',
    spineAssetKey: 'slime_bone',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.48,
    baseDamage: 22.5,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime'],
    levelOverrides: [
      {
        minLevel: 61,
        maxLevel: 100,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
      {
        minLevel: 101,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  slimeBoneLucky: {
    id: 'slimeBoneLucky',
    spineAssetKey: 'slime_bone',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.48,
    baseDamage: 22.5,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLuckyLoot],
    tags: ['slime'],
  },
  mushroomSmall: {
    id: 'mushroomSmall',
    spineAssetKey: 'mushroom_small',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.35,
    baseDamage: 12.5,
    damageGrowth: 1.33,
    baseDefense: 2.25,
    defenseGrowth: 1.31,
    speed: 11,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
  },
  mushroomLarge: {
    id: 'mushroomLarge',
    spineAssetKey: 'mushroom_large',
    damageType: 'physical',
    baseHp: 40.5,
    hpGrowth: 4.73,
    baseDamage: 25,
    damageGrowth: 3.38,
    baseDefense: 4.5,
    defenseGrowth: 2.81,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLargeEliteLoot],
    tags: ['mushroom', 'elite'],
  },
  mushroomLargeBoss: {
    id: 'mushroomLargeBoss',
    spineAssetKey: 'mushroom_large',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 6.43,
    baseDamage: 36.26,
    damageGrowth: 1.5,
    baseDefense: 6,
    defenseGrowth: 3.75,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: 0.3,
    lightningResist: -0.3,
    lootTables: [et.mushroomLargeBossLoot],
    abilities: [{ id: 'BossBrain_MushroomLargeBoss' }],
    tags: ['boss', 'mushroom'],
  },
  skelWizard: {
    id: 'skelWizard',
    spineAssetKey: 'skel_wizard',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 1.48,
    baseDamage: 15,
    damageGrowth: 1.5,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 6,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton'],
  },
  skelGreatSword: {
    id: 'skelGreatSword',
    spineAssetKey: 'skel_greatSword',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 2.03,
    baseDamage: 26.26,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 5,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  skelGreatSwordLucky: {
    id: 'skelGreatSwordLucky',
    spineAssetKey: 'skel_greatSword',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 2.03,
    baseDamage: 26.26,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 5,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLuckyLoot],
    tags: ['skeleton', 'armed'],
  },
  skelAssassin: {
    id: 'skelAssassin',
    spineAssetKey: 'skel_assassin',
    damageType: 'physical',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 23.76,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.25,
    speed: 13,
    crit: 0,
    dodge: 0.03,
    lightningResist: -0.2,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  cannibal: {
    id: 'cannibal',
    spineAssetKey: 'cannibal',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.55,
    baseDefense: 6,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkBat: {
    id: 'darkBat',
    spineAssetKey: 'dark_bat',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.3,
    baseDamage: 18.76,
    damageGrowth: 1.32,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 15,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkShaman: {
    id: 'darkShaman',
    spineAssetKey: 'dark_shaman',
    damageType: 'shadow',
    baseHp: 10.8,
    hpGrowth: 2.03,
    baseDamage: 8.5,
    damageGrowth: 1,
    baseDefense: 6.75,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          { id: 'CastSilence', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  darkChild: {
    id: 'darkChild',
    spineAssetKey: 'dark_child',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 1.55,
    baseDamage: 20,
    damageGrowth: 1.36,
    baseDefense: 3,
    defenseGrowth: 1.25,
    speed: 5,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkBigGuy: {
    id: 'darkBigGuy',
    spineAssetKey: 'dark_bigGuy',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.93,
    baseDamage: 23.76,
    damageGrowth: 1.69,
    baseDefense: 6,
    defenseGrowth: 1.25,
    speed: 11,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkBigGuyLucky: {
    id: 'darkBigGuyLucky',
    spineAssetKey: 'dark_bigGuy',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 2.03,
    baseDamage: 23.76,
    damageGrowth: 1.69,
    baseDefense: 6,
    defenseGrowth: 1.25,
    speed: 11,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLuckyLoot],
    tags: ['dark'],
  },
  darkHand: {
    id: 'darkHand',
    spineAssetKey: 'dark_hand',
    damageType: 'shadow',
    baseHp: 9,
    hpGrowth: 1.3,
    baseDamage: 12,
    damageGrowth: 0.88,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkWizard: {
    id: 'darkWizard',
    spineAssetKey: 'dark_wiz',
    damageType: 'shadow',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 0.88,
    baseDefense: 3,
    defenseGrowth: 1.25,
    speed: 10,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkGiantHorns: {
    id: 'darkGiantHorns',
    spineAssetKey: 'dark_giantHorns',
    damageType: 'physical',
    baseHp: 45,
    hpGrowth: 5.06,
    baseDamage: 38.76,
    damageGrowth: 3.13,
    baseDefense: 11.25,
    defenseGrowth: 3.75,
    speed: 11,
    crit: 0.05,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    shadowResist: 0.3,
    lootTables: [et.darkBossLoot],
    abilities: [{ id: 'LightningOnCrit' }],
    tags: ['dark', 'elite'],
  },
  darkWorm: {
    id: 'darkWorm',
    spineAssetKey: 'dark_worm',
    damageType: 'physical',
    baseHp: 16.2,
    hpGrowth: 1.38,
    baseDamage: 23.76,
    damageGrowth: 1.3,
    baseDefense: 3.75,
    defenseGrowth: 1.25,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
    levelOverrides: [
      {
        minLevel: 41,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  darkSpider: {
    id: 'darkSpider',
    spineAssetKey: 'dark_spider',
    damageType: 'physical',
    baseHp: 9,
    hpGrowth: 1.48,
    baseDamage: 13.76,
    damageGrowth: 1.38,
    baseDefense: 2.25,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          { id: 'PoisonOnAttackScaled', params: { scalePercent: 0.15 } },
        ],
      },
    ],
  },
  darkDemon: {
    id: 'darkDemon',
    spineAssetKey: 'dark_demon',
    damageType: 'shadow',
    baseHp: 54,
    hpGrowth: 5.74,
    baseDamage: 18.76,
    damageGrowth: 1.13,
    baseDefense: 9,
    defenseGrowth: 5,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    lightningResist: -0.3,
    shadowResist: 0.3,
    lootTables: [et.darkDemonBossLoot],
    abilities: [{ id: 'BossBrain_DarkDemon' }],
    tags: ['boss', 'dark', 'armed'],
  },
  mushroomChild: {
    id: 'mushroomChild',
    spineAssetKey: 'mushroom_child',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 1.3,
    baseDamage: 12,
    damageGrowth: 1.2,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
    levelOverrides: [
      {
        minLevel: 101,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastHypnotize', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  mushroomFrog: {
    id: 'mushroomFrog',
    spineAssetKey: 'mushroom_frog',
    damageType: 'physical',
    baseHp: 15.3,
    hpGrowth: 1.48,
    baseDamage: 12.5,
    damageGrowth: 1.38,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 7,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom', 'blue'],
  },
  mushroomSoldierLucky: {
    id: 'mushroomSoldierLucky',
    spineAssetKey: 'mushroom_soldier',
    damageType: 'physical',
    baseHp: 16.2,
    hpGrowth: 1.48,
    baseDamage: 21.26,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLuckyLoot],
    tags: ['mushroom', 'armed', 'red'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 3 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  mushroomSoldier: {
    id: 'mushroomSoldier',
    spineAssetKey: 'mushroom_soldier',
    damageType: 'physical',
    baseHp: 16.2,
    hpGrowth: 1.76,
    baseDamage: 21.26,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom', 'armed', 'red'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 3 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  livingArmor: {
    id: 'livingArmor',
    spineAssetKey: 'livingArmor',
    damageType: 'lightning',
    baseHp: 78.75,
    hpGrowth: 5.4,
    baseDamage: 37.5,
    damageGrowth: 1,
    baseDefense: 11.25,
    defenseGrowth: 4.69,
    speed: 10,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lightningResist: 0.3,
    shadowResist: 0.6,
    lootTables: [et.livingArmorBossLoot],
    abilities: [{ id: 'BossBrain_LivingArmor' }],
    tags: ['boss', 'skeleton', 'armed'],
  },
  mushroomMonster: {
    id: 'mushroomMonster',
    spineAssetKey: 'mushroom_monster',
    damageType: 'physical',
    baseHp: 15.75,
    hpGrowth: 1.48,
    baseDamage: 21.26,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
  },
  mushroomTeeth: {
    id: 'mushroomTeeth',
    spineAssetKey: 'mushroom_teeth',
    damageType: 'physical',
    baseHp: 12.15,
    hpGrowth: 1.48,
    baseDamage: 25,
    damageGrowth: 1.44,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          {
            id: 'PoisonOnAttackScaled',
            params: { scalePercent: 0.25, applyChance: 0.25 },
          },
        ],
      },
    ],
  },
  woodGolem: {
    id: 'woodGolem',
    spineAssetKey: 'wood_golem',
    damageType: 'physical',
    baseHp: 81,
    hpGrowth: 7.43,
    baseDamage: 31.26,
    damageGrowth: 1,
    baseDefense: 6,
    defenseGrowth: 6.25,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: -0.3,
    iceResist: 0.4,
    lightningResist: 0.6,
    lootTables: [et.woodGolemBossLoot],
    abilities: [{ id: 'BossBrain_WoodGolem' }],
    tags: ['boss', 'golem'],
  },
  icyWoodGolem: {
    id: 'icyWoodGolem',
    spineAssetKey: 'icyWood_golem',
    damageType: 'ice',
    baseHp: 81,
    hpGrowth: 7.43,
    baseDamage: 31.26,
    damageGrowth: 1,
    baseDefense: 6,
    defenseGrowth: 6.25,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lightningResist: 0.6,
    lootTables: [et.woodGolemBossLoot],
    abilities: [{ id: 'BossBrain_IcyWoodGolem' }],
    tags: ['boss', 'golem'],
  },
  woodOctopus: {
    id: 'woodOctopus',
    spineAssetKey: 'wood_octopus',
    damageType: 'physical',
    baseHp: 10.35,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 1.38,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
    levelOverrides: [
      {
        minLevel: 101,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          { id: 'CastHypnotize', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  woodRoof: {
    id: 'woodRoof',
    spineAssetKey: 'wood_roof',
    damageType: 'physical',
    baseHp: 18.45,
    hpGrowth: 2.16,
    baseDamage: 21.26,
    damageGrowth: 1.88,
    baseDefense: 4.5,
    defenseGrowth: 1.63,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  robotNo1: {
    id: 'robotNo1',
    spineAssetKey: 'robot_no1',
    damageType: 'lightning',
    baseHp: 9.45,
    hpGrowth: 1.62,
    baseDamage: 12,
    damageGrowth: 0.94,
    baseDefense: 4.5,
    defenseGrowth: 1.5,
    speed: 10,
    crit: 0,
    dodge: 0,
    lightningResist: 0.2,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo2: {
    id: 'robotNo2',
    spineAssetKey: 'robot_no2',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.62,
    baseDamage: 15,
    damageGrowth: 1.38,
    baseDefense: 6,
    defenseGrowth: 1.5,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    shadowResist: 0.2,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo3: {
    id: 'robotNo3',
    spineAssetKey: 'robot_no3',
    damageType: 'physical',
    baseHp: 11.7,
    hpGrowth: 1.69,
    baseDamage: 25,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.5,
    speed: 6,
    crit: 0.03,
    dodge: 0,
    shadowResist: 0.2,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo4: {
    id: 'robotNo4',
    spineAssetKey: 'robot_no4',
    damageType: 'ice',
    baseHp: 11.7,
    hpGrowth: 2.03,
    baseDamage: 15,
    damageGrowth: 0.94,
    baseDefense: 6,
    defenseGrowth: 1.38,
    speed: 10,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.3,
    iceResist: 0.3,
    lightningResist: -0.3,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo5: {
    id: 'robotNo5',
    spineAssetKey: 'robot_no5',
    damageType: 'fire',
    baseHp: 12.15,
    hpGrowth: 2.03,
    baseDamage: 12.5,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 1.5,
    speed: 7,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lootTables: [et.robotLoot],
    tags: ['robot'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          {
            id: 'PoisonOnAttackScaled',
            params: { scalePercent: 0.2, applyChance: 0.4 },
          },
        ],
      },
    ],
  },
  robotNo5Lucky: {
    id: 'robotNo5Lucky',
    spineAssetKey: 'robot_no5',
    damageType: 'fire',
    baseHp: 12.15,
    hpGrowth: 2.03,
    baseDamage: 12.5,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 1.5,
    speed: 7,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lootTables: [et.robotLuckyLoot],
    tags: ['robot'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          {
            id: 'PoisonOnAttackScaled',
            params: { scalePercent: 0.2, applyChance: 0.4 },
          },
        ],
      },
    ],
  },
  robotNo6: {
    id: 'robotNo6',
    spineAssetKey: 'robot_no6',
    damageType: 'fire',
    baseHp: 67.5,
    hpGrowth: 7.09,
    baseDamage: 35,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 5,
    speed: 9,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.5,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.robotNo6BossLoot],
    abilities: [{ id: 'BossBrain_RobotNo6' }],
    tags: ['boss', 'robot'],
  },
  robotNo7: {
    id: 'robotNo7',
    spineAssetKey: 'robot_no7',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.49,
    baseDamage: 23.76,
    damageGrowth: 1.38,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.3,
    lightningResist: -0.3,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotBoss: {
    id: 'robotBoss',
    spineAssetKey: 'robot_boss',
    damageType: 'lightning',
    baseHp: 112.5,
    hpGrowth: 8.78,
    baseDamage: 45,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 5,
    speed: 8,
    crit: 0.04,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lootTables: [et.robotBossBossLoot],
    abilities: [{ id: 'BossBrain_RobotBoss' }],
    tags: ['boss', 'robot'],
  },
  poisonDemon: {
    id: 'poisonDemon',
    spineAssetKey: 'poison_demon',
    damageType: 'shadow',
    baseHp: 54,
    hpGrowth: 5.9,
    baseDamage: 18.76,
    damageGrowth: 1.08,
    baseDefense: 9,
    defenseGrowth: 5.5,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: 0.3,
    lootTables: [et.poisonDemonBossLoot],
    abilities: [{ id: 'BossBrain_PoisonDemon' }],
    tags: ['boss', 'dark'],
  },
  blossomGolem: {
    id: 'blossomGolem',
    spineAssetKey: 'blossom_golem',
    damageType: 'physical',
    baseHp: 81,
    hpGrowth: 7.1,
    baseDamage: 31.26,
    damageGrowth: 1.4,
    baseDefense: 6,
    defenseGrowth: 8,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: -0.4,
    shadowResist: 0.5,
    lootTables: [et.blossomGolemBossLoot],
    abilities: [{ id: 'BossBrain_BlossomGolem' }],
    tags: ['boss', 'golem'],
  },
  corruptedSkeleton: {
    id: 'corruptedSkeleton',
    spineAssetKey: 'corrupted_skeleton',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.48,
    baseDamage: 13.76,
    damageGrowth: 1.38,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 10,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  corruptedSkelNoHead: {
    id: 'corruptedSkelNoHead',
    spineAssetKey: 'corrupted_skel_noHead',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    abilities: [
      { id: 'DefaultAttack', params: { weight: 1 } },
      { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
    ],
    tags: ['skeleton'],
  },
  corruptedSkel2Axe: {
    id: 'corruptedSkel2Axe',
    spineAssetKey: 'corrupted_skel_2Axe',
    damageType: 'physical',
    baseHp: 15.3,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  corruptedSkelWizard: {
    id: 'corruptedSkelWizard',
    spineAssetKey: 'corrupted_skel_wizard',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 1.48,
    baseDamage: 15,
    damageGrowth: 1.5,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 6,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    abilities: [
      { id: 'DefaultAttack', params: { weight: 1 } },
      { id: 'CastSilence', params: { weight: 1, recastChance: 0 } },
    ],
    tags: ['skeleton'],
  },
  corruptedSkelAssassin: {
    id: 'corruptedSkelAssassin',
    spineAssetKey: 'corrupted_skel_assassin',
    damageType: 'physical',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 23.76,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.25,
    speed: 13,
    crit: 0,
    dodge: 0.03,
    lightningResist: -0.2,
    lootTables: [et.skeletonLoot],
    abilities: [
      {
        id: 'PoisonOnAttackScaled',
        params: { scalePercent: 0.15, applyChance: 0.7 },
      },
    ],
    tags: ['skeleton', 'armed'],
  },
}
