export const enemyNames: Record<string, string> = {
  golemBaby: 'Baby Golem',
  golemBoar: 'Boar Golem',
  golemMountain: 'Mountain Golem',
  skeleton: 'Warrior Skeleton',
  skel2Axe: 'Barbarian Skeleton',
  skelArcher: 'Ranger Skeleton',
  skelAssassin: 'Assassin Skeleton',
  skelGreatSword: 'Swordsman Skeleton',
  skelNoHead: 'Headless Skeleton',
  skelWizard: 'Wizard Skeleton',
  skelFireHead: 'Flaming Skeleton',
  skelIceHead: 'Ice Flame Skeleton',
  slimeBone: 'Bone Slime',
  slimeKnight: 'Slime Knight',
  slimeBigMouth: 'Chomp Slime',
  slimeCat: 'Cat Slime',
  slimeGems: 'Crystal Slime',
  mushroomSmall: 'Bitey Shroom',
  mushroomLarge: 'Erin-guy',
  mushroomChild: 'Shroomkin',
  mushroomFrog: 'Sporehead',
  mushroomSoldier: 'Sporewarden',
  mushroomMonster: 'Sturdy Sporeborn',
  mushroomTeeth: 'Mawcap',
  mushroomLargeBoss: 'Boss Mushroom',
  cannibal: 'Shadowbearer',
  darkBat: 'Shadow Wing',
  darkChild: 'Shadowkin',
  darkBigGuy: 'Shadow Brute',
  darkHand: 'Arm of Shadow',
  darkShaman: 'Shadowbringer',
  darkSpider: 'Skittering Shadow',
  darkWizard: 'Shadow Conjurer',
  darkWorm: 'Shadow Hatchling',
  darkGiantHorns: 'Hollowhorn',
  darkDemon: 'Umbral Winged Shadeborn',
  woodOctopus: 'Branchclutch',
  woodRoof: 'Stumpkin',
  woodGolem: 'Heartroot Guardian',
  icyWoodGolem: 'Frostroot Guardian',
  plantBigMouth: 'Big Mouth Plant',
  livingArmor: 'Steel Revenant',
  gildedGuardian: 'Gilded Guardian',
  slimeArmored: 'Armored Slime',
  gargoyle: 'Gargoyle',
  evilBook: 'Grouchy Grimoire',
  livingArmorCute: 'Tin Squire',
  livingArmorKnight: 'Iron Revenant',
  livingArmorLight: 'Restless Sentinel',
  livingWall: 'Stonekeep',
  giantWizard: 'Corrupted Scholar',
  mimicChest: 'Mimic',
  robotNo1: 'Y5-Sentry',
  robotNo2: 'KRG-01',
  robotNo3: 'Gen5-HVY',
  robotNo4: 'Medibot-Mark IV',
  robotNo5: 'WasteLogic LX-9',
  robotNo6: 'BRX-7 Sentry Chassis',
  robotNo7: 'Minifax Model B',
  robotBoss: 'Slumbering Guardian-X5',
  corruptedSkeleton: 'Corrupted Warrior Skeleton',
  corruptedSkel2Axe: 'Corrupted Barbarian Skeleton',
  corruptedSkelAssassin: 'Corrupted Skeleton Assassin',
  corruptedSkelNoHead: 'Corrupted Headless Skeleton',
  corruptedSkelWizard: 'Corrupted Skeleton Wizard',
  golemMountainLucky: 'Loaded Mountain Golem',
  slimeBoneLucky: 'Loaded Bone Slime',
  skelGreatSwordLucky: 'Loaded Swordsman Skeleton',
  darkBigGuyLucky: 'Loaded Shadow Brute',
  mushroomSoldierLucky: 'Loaded Sporewarden',
  poisonDemon: 'Toxic Winged Shadeborn',
  blossomGolem: 'Blossom Golem',
  robotNo5Lucky: 'Loaded Robot 5',
}
