export const enemyNames: Record<string, string> = {
  golemBaby: 'Baby Golem',
  slimeKnight: 'Slime Knight',
  slimeBigMouth: 'Chomp Slime',
  slimeCat: 'Cat Slime',
  slimeGems: 'Crystal Slime',
  skeleton: 'Warrior Skeleton',
  skelNoHead: 'Headless Skeleton',
  golemMountain: 'Mountain Golem',
  golemMountainLucky: 'Loaded Mountain Golem',
  golemBoar: 'Boar Golem',
  skelFireHead: 'Flaming Skeleton',
  skelIceHead: 'Ice Flame Skeleton',
  skelArcher: 'Ranger Skeleton',
  skel2Axe: 'Barbarian Skeleton',
  slimeBone: 'Bone Slime',
  slimeBoneLucky: 'Loaded Bone Slime',
  mushroomSmall: 'Bitey Shroom',
  mushroomLarge: 'Erin-guy',
  mushroomLargeBoss: 'Boss Mushroom',
  skelWizard: 'Wizard Skeleton',
  skelGreatSword: 'Swordsman Skeleton',
  skelGreatSwordLucky: 'Loaded Swordsman Skeleton',
  skelAssassin: 'Assassin Skeleton',
  cannibal: 'Shadowbearer',
  darkBat: 'Shadow Wing',
  darkShaman: 'Shadowbringer',
  darkChild: 'Shadowkin',
  darkBigGuy: 'Shadow Brute',
  darkBigGuyLucky: 'Loaded Shadow Brute',
  darkHand: 'Arm of Shadow',
  darkWizard: 'Shadow Conjurer',
  darkGiantHorns: 'Hollowhorn',
  darkWorm: 'Shadow Hatchling',
  darkSpider: 'Skittering Shadow',
  darkDemon: 'Umbral Winged Shadeborn',
  mushroomChild: 'Shroomkin',
  mushroomFrog: 'Sporehead',
  mushroomSoldierLucky: 'Loaded Sporehead',
  mushroomSoldier: 'Sporewarden',
  livingArmor: 'Steel Revenant',
  mushroomMonster: 'Sturdy Sporeborn',
  mushroomTeeth: 'Mawcap',
  woodGolem: 'Heartroot Guardian',
  icyWoodGolem: 'Frostroot Guardian',
  woodOctopus: 'Branchclutch',
  woodRoof: 'Stumpkin',
  robotNo1: 'Y5-Sentry',
  robotNo2: 'KRG-01',
  robotNo3: 'Gen5-HVY',
  robotNo4: 'Medibot-Mark IV',
  robotNo5: 'WasteLogic LX-9',
  robotNo5Lucky: 'Loaded WasteLogic LX-9',
  robotNo6: 'BRX-7 Sentry Chassis',
  robotNo7: 'Minifax Model B',
  robotBoss: 'Slumbering Guardian-X5',
}
