import type { Enemy } from '../types'
import { et } from './loot'

export const z3: Record<string, Enemy> = {
  golemBaby: {
    id: 'golemBaby',
    name: 'Baby Golem',
    spineAssetKey: 'golem_baby',
    damageType: 'physical',
    baseHp: 6.75,
    hpGrowth: 1.48,
    baseDamage: 12.5,
    damageGrowth: 1.38,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
  },
  slimeKnight: {
    id: 'slimeKnight',
    name: 'Slime Knight',
    spineAssetKey: 'slime_knight',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.55,
    baseDamage: 15,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.31,
    speed: 11,
    crit: 0.03,
    dodge: 0,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime', 'armed'],
  },
  slimeBigMouth: {
    id: 'slimeBigMouth',
    name: 'Chomp Slime',
    spineAssetKey: 'slime_bigMouth',
    damageType: 'physical',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 16.26,
    damageGrowth: 1.38,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 11,
    crit: 0,
    dodge: 0,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime', 'blue'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  slimeCat: {
    id: 'slimeCat',
    name: 'Cat Slime',
    spineAssetKey: 'slime_cat',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.48,
    baseDamage: 16.26,
    damageGrowth: 1.38,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 12,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime'],
  },
  slimeGems: {
    id: 'slimeGems',
    name: 'Crystal Slime',
    spineAssetKey: 'slime_gems',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 1.38,
    baseDefense: 7.5,
    defenseGrowth: 1.31,
    speed: 7,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime', 'armed'],
  },
  skeleton: {
    id: 'skeleton',
    name: 'Warrior Skeleton',
    spineAssetKey: 'skeleton',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.48,
    baseDamage: 13.76,
    damageGrowth: 1.38,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 10,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  skelNoHead: {
    id: 'skelNoHead',
    name: 'Headless Skeleton',
    spineAssetKey: 'skel_noHead',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton'],
  },
  golemMountain: {
    id: 'golemMountain',
    name: 'Mountain Golem',
    spineAssetKey: 'golem_mountain',
    damageType: 'physical',
    baseHp: 13.05,
    hpGrowth: 2.03,
    baseDamage: 31.26,
    damageGrowth: 1.69,
    baseDefense: 7.5,
    defenseGrowth: 1.56,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem', 'armed'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  golemMountainLucky: {
    id: 'golemMountainLucky',
    name: 'Loaded Mountain Golem',
    spineAssetKey: 'golem_mountain',
    damageType: 'physical',
    baseHp: 13.05,
    hpGrowth: 2.03,
    baseDamage: 31.26,
    damageGrowth: 1.69,
    baseDefense: 7.5,
    defenseGrowth: 1.56,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLuckyLoot],
    tags: ['golem', 'armed'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  golemBoar: {
    id: 'golemBoar',
    name: 'Boar Golem',
    spineAssetKey: 'golem_boar',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 1.44,
    baseDefense: 6,
    defenseGrowth: 1.37,
    speed: 9,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
  },
  skelFireHead: {
    id: 'skelFireHead',
    name: 'Flaming Skeleton',
    spineAssetKey: 'skel_fireHead',
    damageType: 'fire',
    baseHp: 22.5,
    hpGrowth: 7.43,
    baseDamage: 15,
    damageGrowth: 1,
    baseDefense: 3.75,
    defenseGrowth: 5.31,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.6,
    iceResist: -0.3,
    lightningResist: -0.3,
    shadowResist: -0.3,
    lootTables: [et.fireHeadBossLoot],
    abilities: [{ id: 'BossBrain_SkeletonFireHead' }],
    tags: ['boss', 'skeleton', 'red'],
    spineScale: 0.3,
  },
  skelIceHead: {
    id: 'skelIceHead',
    name: 'Ice Flame Skeleton',
    spineAssetKey: 'skel_iceHead',
    damageType: 'ice',
    baseHp: 45,
    hpGrowth: 7.43,
    baseDamage: 25,
    damageGrowth: 1.13,
    baseDefense: 11.25,
    defenseGrowth: 4.69,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: -0.3,
    iceResist: 0.6,
    lightningResist: -0.3,
    shadowResist: -0.3,
    lootTables: [et.fireHeadBossLoot],
    abilities: [{ id: 'BossBrain_SkeletonIceHead' }],
    tags: ['boss', 'skeleton', 'blue'],
    spineScale: 0.3,
  },
  skelArcher: {
    id: 'skelArcher',
    name: 'Ranger Skeleton',
    spineAssetKey: 'skel_archer',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.48,
    baseDamage: 15,
    damageGrowth: 1.44,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 12,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  skel2Axe: {
    id: 'skel2Axe',
    name: 'Barbarian Skeleton',
    spineAssetKey: 'skel_2Axe',
    damageType: 'physical',
    baseHp: 15.3,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  slimeBone: {
    id: 'slimeBone',
    name: 'Bone Slime',
    spineAssetKey: 'slime_bone',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.48,
    baseDamage: 22.5,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLoot],
    tags: ['slime'],
    levelOverrides: [
      {
        minLevel: 61,
        maxLevel: 100,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
      {
        minLevel: 101,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  slimeBoneLucky: {
    id: 'slimeBoneLucky',
    name: 'Loaded Bone Slime',
    spineAssetKey: 'slime_bone',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.48,
    baseDamage: 22.5,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.2,
    iceResist: 0.3,
    lightningResist: 0.3,
    lootTables: [et.slimeLuckyLoot],
    tags: ['slime'],
  },
  mushroomSmall: {
    id: 'mushroomSmall',
    name: 'Bitey Shroom',
    spineAssetKey: 'mushroom_small',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.35,
    baseDamage: 12.5,
    damageGrowth: 1.33,
    baseDefense: 2.25,
    defenseGrowth: 1.31,
    speed: 11,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
  },
  mushroomLarge: {
    id: 'mushroomLarge',
    name: 'Erin-guy',
    spineAssetKey: 'mushroom_large',
    damageType: 'physical',
    baseHp: 40.5,
    hpGrowth: 4.73,
    baseDamage: 25,
    damageGrowth: 3.38,
    baseDefense: 4.5,
    defenseGrowth: 2.81,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLargeEliteLoot],
    tags: ['mushroom', 'elite'],
    spineScale: 0.4,
  },
  mushroomLargeBoss: {
    id: 'mushroomLargeBoss',
    name: 'Boss Mushroom',
    spineAssetKey: 'mushroom_large',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 6.43,
    baseDamage: 36.26,
    damageGrowth: 1.5,
    baseDefense: 6,
    defenseGrowth: 3.75,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: 0.3,
    lightningResist: -0.3,
    lootTables: [et.mushroomLargeBossLoot],
    abilities: [{ id: 'BossBrain_MushroomLargeBoss' }],
    tags: ['boss', 'mushroom'],
    spineScale: 0.4,
  },
  skelWizard: {
    id: 'skelWizard',
    name: 'Wizard Skeleton',
    spineAssetKey: 'skel_wizard',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 1.48,
    baseDamage: 15,
    damageGrowth: 1.5,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 6,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton'],
  },
  skelGreatSword: {
    id: 'skelGreatSword',
    name: 'Swordsman Skeleton',
    spineAssetKey: 'skel_greatSword',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 2.03,
    baseDamage: 26.26,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 5,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  skelGreatSwordLucky: {
    id: 'skelGreatSwordLucky',
    name: 'Loaded Swordsman Skeleton',
    spineAssetKey: 'skel_greatSword',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 2.03,
    baseDamage: 26.26,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 5,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLuckyLoot],
    tags: ['skeleton', 'armed'],
  },
  skelAssassin: {
    id: 'skelAssassin',
    name: 'Assassin Skeleton',
    spineAssetKey: 'skel_assassin',
    damageType: 'physical',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 23.76,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.25,
    speed: 13,
    crit: 0,
    dodge: 0.03,
    lightningResist: -0.2,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  cannibal: {
    id: 'cannibal',
    name: 'Shadowbearer',
    spineAssetKey: 'cannibal',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.55,
    baseDefense: 6,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkBat: {
    id: 'darkBat',
    name: 'Shadow Wing',
    spineAssetKey: 'dark_bat',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.3,
    baseDamage: 18.76,
    damageGrowth: 1.32,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 15,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkShaman: {
    id: 'darkShaman',
    name: 'Shadowbringer',
    spineAssetKey: 'dark_shaman',
    damageType: 'shadow',
    baseHp: 10.8,
    hpGrowth: 2.03,
    baseDamage: 8.5,
    damageGrowth: 1,
    baseDefense: 6.75,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          { id: 'CastSilence', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  darkChild: {
    id: 'darkChild',
    name: 'Shadowkin',
    spineAssetKey: 'dark_child',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 1.55,
    baseDamage: 20,
    damageGrowth: 1.36,
    baseDefense: 3,
    defenseGrowth: 1.25,
    speed: 5,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkBigGuy: {
    id: 'darkBigGuy',
    name: 'Shadow Brute',
    spineAssetKey: 'dark_bigGuy',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 1.93,
    baseDamage: 23.76,
    damageGrowth: 1.69,
    baseDefense: 6,
    defenseGrowth: 1.25,
    speed: 11,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkBigGuyLucky: {
    id: 'darkBigGuyLucky',
    name: 'Loaded Shadow Brute',
    spineAssetKey: 'dark_bigGuy',
    damageType: 'physical',
    baseHp: 12.6,
    hpGrowth: 2.03,
    baseDamage: 23.76,
    damageGrowth: 1.69,
    baseDefense: 6,
    defenseGrowth: 1.25,
    speed: 11,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLuckyLoot],
    tags: ['dark'],
  },
  darkHand: {
    id: 'darkHand',
    name: 'Arm of Shadow',
    spineAssetKey: 'dark_hand',
    damageType: 'shadow',
    baseHp: 9,
    hpGrowth: 1.3,
    baseDamage: 12,
    damageGrowth: 0.88,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkWizard: {
    id: 'darkWizard',
    name: 'Shadow Conjurer',
    spineAssetKey: 'dark_wiz',
    damageType: 'shadow',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 0.88,
    baseDefense: 3,
    defenseGrowth: 1.25,
    speed: 10,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
  },
  darkGiantHorns: {
    id: 'darkGiantHorns',
    name: 'Hollowhorn',
    spineAssetKey: 'dark_giantHorns',
    damageType: 'physical',
    baseHp: 45,
    hpGrowth: 5.06,
    baseDamage: 38.76,
    damageGrowth: 3.13,
    baseDefense: 11.25,
    defenseGrowth: 3.75,
    speed: 11,
    crit: 0.05,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    shadowResist: 0.3,
    lootTables: [et.darkBossLoot],
    abilities: [{ id: 'LightningOnCrit' }],
    tags: ['dark', 'elite'],
    spineScale: 0.3,
  },
  darkWorm: {
    id: 'darkWorm',
    name: 'Shadow Hatchling',
    spineAssetKey: 'dark_worm',
    damageType: 'physical',
    baseHp: 16.2,
    hpGrowth: 1.38,
    baseDamage: 23.76,
    damageGrowth: 1.3,
    baseDefense: 3.75,
    defenseGrowth: 1.25,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
    levelOverrides: [
      {
        minLevel: 41,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  darkSpider: {
    id: 'darkSpider',
    name: 'Skittering Shadow',
    spineAssetKey: 'dark_spider',
    damageType: 'physical',
    baseHp: 9,
    hpGrowth: 1.48,
    baseDamage: 13.76,
    damageGrowth: 1.38,
    baseDefense: 2.25,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.2,
    iceResist: 0.2,
    lootTables: [et.darkLoot],
    tags: ['dark'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          { id: 'PoisonOnAttackScaled', params: { scalePercent: 0.15 } },
        ],
      },
    ],
  },
  darkDemon: {
    id: 'darkDemon',
    name: 'Umbral Winged Shadeborn',
    spineAssetKey: 'dark_demon',
    damageType: 'shadow',
    baseHp: 54,
    hpGrowth: 5.74,
    baseDamage: 18.76,
    damageGrowth: 1.13,
    baseDefense: 9,
    defenseGrowth: 5,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    lightningResist: -0.3,
    shadowResist: 0.3,
    lootTables: [et.darkDemonBossLoot],
    abilities: [{ id: 'BossBrain_DarkDemon' }],
    tags: ['boss', 'dark', 'armed'],
    spineScale: 0.3,
  },
  poisonDemon: {
    id: 'poisonDemon',
    name: 'Toxic Winged Shadeborn',
    spineAssetKey: 'poison_demon',
    damageType: 'shadow',
    baseHp: 54,
    hpGrowth: 5.9,
    baseDamage: 18.76,
    damageGrowth: 1.08,
    baseDefense: 9,
    defenseGrowth: 5.5,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: 0.3,
    lootTables: [et.poisonDemonBossLoot],
    abilities: [{ id: 'BossBrain_PoisonDemon' }],
    tags: ['boss', 'dark'],
    spineScale: 0.3,
  },
  mushroomChild: {
    id: 'mushroomChild',
    name: 'Shroomkin',
    spineAssetKey: 'mushroom_child',
    damageType: 'physical',
    baseHp: 11.25,
    hpGrowth: 1.3,
    baseDamage: 12,
    damageGrowth: 1.2,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
    levelOverrides: [
      {
        minLevel: 101,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastHypnotize', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  mushroomFrog: {
    id: 'mushroomFrog',
    name: 'Sporehead',
    spineAssetKey: 'mushroom_frog',
    damageType: 'physical',
    baseHp: 15.3,
    hpGrowth: 1.48,
    baseDamage: 12.5,
    damageGrowth: 1.38,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 7,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom', 'blue'],
  },
  mushroomSoldierLucky: {
    id: 'mushroomSoldierLucky',
    name: 'Loaded Sporewarden',
    spineAssetKey: 'mushroom_soldier',
    damageType: 'physical',
    baseHp: 16.2,
    hpGrowth: 1.48,
    baseDamage: 21.26,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLuckyLoot],
    tags: ['mushroom', 'armed', 'red'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 3 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  mushroomSoldier: {
    id: 'mushroomSoldier',
    name: 'Sporewarden',
    spineAssetKey: 'mushroom_soldier',
    damageType: 'physical',
    baseHp: 16.2,
    hpGrowth: 1.76,
    baseDamage: 21.26,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom', 'armed', 'red'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 3 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
        ],
      },
    ],
  },
  livingArmor: {
    id: 'livingArmor',
    name: 'Steel Revenant',
    spineAssetKey: 'livingArmor',
    damageType: 'lightning',
    baseHp: 78.75,
    hpGrowth: 5.4,
    baseDamage: 37.5,
    damageGrowth: 1,
    baseDefense: 11.25,
    defenseGrowth: 4.69,
    speed: 10,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lightningResist: 0.3,
    shadowResist: 0.6,
    lootTables: [et.livingArmorBossLoot],
    abilities: [{ id: 'BossBrain_LivingArmor' }],
    tags: ['boss', 'skeleton', 'armed'],
    spineScale: 0.25,
  },
  gildedGuardian: {
    id: 'gildedGuardian',
    name: 'Gilded Guardian',
    spineAssetKey: 'gildedGuardian',
    damageType: 'lightning',
    baseHp: 70,
    hpGrowth: 6.8,
    baseDamage: 30,
    damageGrowth: 0.95,
    baseDefense: 12,
    defenseGrowth: 4.5,
    speed: 10,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    iceResist: -0.3,
    fireResist: 0.3,
    shadowResist: 0.6,
    lootTables: [et.gildedGuardianBossLoot],
    abilities: [{ id: 'BossBrain_GildedGuardian' }],
    tags: ['boss', 'skeleton', 'armed'],
    spineScale: 0.25,
  },
  slimeArmored: {
    id: 'slimeArmored',
    name: 'Armored Slime',
    spineAssetKey: 'ArmoredSlime',
    damageType: 'physical',
    baseHp: 16,
    hpGrowth: 1.95,
    baseDamage: 13,
    damageGrowth: 1.55,
    baseDefense: 8.5,
    defenseGrowth: 1.38,
    speed: 9,
    crit: 0,
    dodge: 0,
    iceResist: 0.3,
    lightningResist: -0.3,
    shadowResist: 0.3,
    lootTables: [et.slimeLoot],
    levelOverrides: [
      { minLevel: 81, abilities: [{ id: 'PoisonOnAttackScaled' }] },
    ],
    tags: ['slime', 'armed'],
  },
  gargoyle: {
    id: 'gargoyle',
    name: 'Gargoyle',
    spineAssetKey: 'Gargoyle',
    damageType: 'shadow',
    baseHp: 15,
    hpGrowth: 2.1,
    baseDamage: 19,
    damageGrowth: 1.55,
    baseDefense: 7,
    defenseGrowth: 1.8,
    speed: 7,
    crit: 0,
    dodge: 0.08,
    lightningResist: -0.3,
    abilities: [
      { id: 'DefaultAttack', params: { weight: 2 } },
      { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
    ],
    lootTables: [et.darkLoot],
    levelOverrides: [
      {
        minLevel: 81,
        resistOverrides: { fireResist: 0.2, iceResist: 0.2, shadowResist: 0.2 },
      },
    ],
    tags: ['dark'],
  },
  livingArmorCute: {
    id: 'livingArmorCute',
    name: 'Tin Squire',
    spineAssetKey: 'livingArmorCute',
    damageType: 'physical',
    baseHp: 12,
    hpGrowth: 1.55,
    baseDamage: 14,
    damageGrowth: 1.58,
    baseDefense: 8,
    defenseGrowth: 1.38,
    speed: 9,
    crit: 0.05,
    dodge: 0,
    lootTables: [et.skeletonLoot],
    levelOverrides: [
      {
        minLevel: 101,
        abilities: [
          { id: 'LowHpCritBoostAbility' },
          { id: 'MaxHpCritBoostAbility' },
        ],
      },
    ],
    tags: ['skeleton', 'armed'],
    spineScale: 0.16,
  },
  livingArmorKnight: {
    id: 'livingArmorKnight',
    name: 'Iron Revenant',
    spineAssetKey: 'livingArmorKnight',
    damageType: 'physical',
    baseHp: 50,
    hpGrowth: 5.2,
    baseDamage: 30,
    damageGrowth: 3.05,
    baseDefense: 15,
    defenseGrowth: 4,
    speed: 9,
    crit: 0.08,
    dodge: 0,
    hypnotizeResist: 0.3,
    weakResist: 0.2,
    vulnerableResist: 0.2,
    abilities: [{ id: 'LowHpCritBoostAbility' }],
    lootTables: [et.livingArmorKnightEliteLoot],
    tags: ['skeleton', 'armed', 'elite'],
    spineScale: 0.22,
  },
  livingArmorLight: {
    id: 'livingArmorLight',
    name: 'Restless Sentinel',
    spineAssetKey: 'livingArmorLight',
    damageType: 'lightning',
    baseHp: 9,
    hpGrowth: 1.38,
    baseDamage: 12,
    damageGrowth: 1.01,
    baseDefense: 3,
    defenseGrowth: 1.2,
    speed: 11,
    crit: 0,
    dodge: 0,
    abilities: [{ id: 'LightningOnTurnStart' }],
    lootTables: [et.skeletonLoot],
    levelOverrides: [
      {
        minLevel: 101,
        abilities: [
          { id: 'LightningOnTurnStart' },
          { id: 'LightningOnAttack' },
        ],
      },
    ],
    tags: ['skeleton', 'armed'],
    spineScale: 0.17,
  },
  livingWall: {
    id: 'livingWall',
    name: 'Stonekeep',
    spineAssetKey: 'livingWallBoss',
    damageType: 'physical',
    baseHp: 120,
    hpGrowth: 7,
    baseDamage: 32,
    damageGrowth: 1,
    baseDefense: 28,
    defenseGrowth: 9,
    speed: 10,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.6,
    iceResist: 0.3,
    lightningResist: 0.3,
    shadowResist: 0.3,
    silenceResist: 1,
    hypnotizeResist: 1,
    lootTables: [et.livingWallBossLoot],
    abilities: [{ id: 'BossBrain_LivingWall' }],
    tags: ['boss', 'wall'],
    spineScale: 0.25,
  },
  giantWizard: {
    id: 'giantWizard',
    name: 'Corrupted Scholar',
    spineAssetKey: 'GiantWizardBoss',
    damageType: 'shadow',
    baseHp: 80,
    hpGrowth: 6.8,
    baseDamage: 32,
    damageGrowth: 0.9,
    baseDefense: 10,
    defenseGrowth: 7.1,
    speed: 9,
    crit: 0.06,
    dodge: 0.06,
    fireResist: 0.6,
    iceResist: 0.6,
    lightningResist: 0.6,
    shadowResist: 0,
    lootTables: [et.giantWizardBossLoot],
    abilities: [{ id: 'BossBrain_GiantWizard' }],
    tags: ['boss', 'wizard'],
    spineScale: 0.25,
  },
  mimicChest: {
    id: 'mimicChest',
    name: 'Mimic',
    spineAssetKey: 'mimicChest',
    damageType: 'physical',
    baseHp: 11,
    hpGrowth: 1.48,
    baseDamage: 21,
    damageGrowth: 1.45,
    baseDefense: 5,
    defenseGrowth: 1.34,
    speed: 10,
    crit: 0,
    dodge: 0,
    fireResist: -0.3,
    lootTables: [et.mimicLoot],
    levelOverrides: [
      { minLevel: 81, abilities: [{ id: 'ApplyVulnerableOnAttack' }] },
    ],
    tags: ['dark'],
  },
  mushroomMonster: {
    id: 'mushroomMonster',
    name: 'Sturdy Sporeborn',
    spineAssetKey: 'mushroom_monster',
    damageType: 'physical',
    baseHp: 15.75,
    hpGrowth: 1.48,
    baseDamage: 21.26,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
  },
  mushroomTeeth: {
    id: 'mushroomTeeth',
    name: 'Mawcap',
    spineAssetKey: 'mushroom_teeth',
    damageType: 'physical',
    baseHp: 12.15,
    hpGrowth: 1.48,
    baseDamage: 25,
    damageGrowth: 1.44,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lootTables: [et.mushroomLoot],
    tags: ['mushroom'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          {
            id: 'PoisonOnAttackScaled',
            params: { scalePercent: 0.25, applyChance: 0.25 },
          },
        ],
      },
    ],
  },
  woodGolem: {
    id: 'woodGolem',
    name: 'Heartroot Guardian',
    spineAssetKey: 'wood_golem',
    damageType: 'physical',
    baseHp: 81,
    hpGrowth: 7.43,
    baseDamage: 31.26,
    damageGrowth: 1,
    baseDefense: 6,
    defenseGrowth: 6.25,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: -0.3,
    iceResist: 0.4,
    lightningResist: 0.6,
    lootTables: [et.woodGolemBossLoot],
    abilities: [{ id: 'BossBrain_WoodGolem' }],
    tags: ['boss', 'golem'],
  },
  blossomGolem: {
    id: 'blossomGolem',
    name: 'Blossom Golem',
    spineAssetKey: 'blossom_golem',
    damageType: 'physical',
    baseHp: 81,
    hpGrowth: 7.1,
    baseDamage: 31.26,
    damageGrowth: 1.4,
    baseDefense: 6,
    defenseGrowth: 8,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: -0.4,
    shadowResist: 0.5,
    lootTables: [et.blossomGolemBossLoot],
    abilities: [{ id: 'BossBrain_BlossomGolem' }],
    tags: ['boss', 'golem'],
  },
  icyWoodGolem: {
    id: 'icyWoodGolem',
    name: 'Frostroot Guardian',
    spineAssetKey: 'icyWood_golem',
    damageType: 'ice',
    baseHp: 81,
    hpGrowth: 7.43,
    baseDamage: 31.26,
    damageGrowth: 1,
    baseDefense: 6,
    defenseGrowth: 6.25,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lightningResist: 0.6,
    lootTables: [et.woodGolemBossLoot],
    abilities: [{ id: 'BossBrain_IcyWoodGolem' }],
    tags: ['boss', 'golem'],
  },
  woodOctopus: {
    id: 'woodOctopus',
    name: 'Branchclutch',
    spineAssetKey: 'wood_octopus',
    damageType: 'physical',
    baseHp: 10.35,
    hpGrowth: 1.48,
    baseDamage: 17.5,
    damageGrowth: 1.38,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
    levelOverrides: [
      {
        minLevel: 101,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 2 } },
          { id: 'CastHypnotize', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  woodRoof: {
    id: 'woodRoof',
    name: 'Stumpkin',
    spineAssetKey: 'wood_roof',
    damageType: 'physical',
    baseHp: 18.45,
    hpGrowth: 2.16,
    baseDamage: 21.26,
    damageGrowth: 1.88,
    baseDefense: 4.5,
    defenseGrowth: 1.63,
    speed: 8,
    crit: 0,
    dodge: 0,
    lightningResist: 0.3,
    shadowResist: 0.2,
    lootTables: [et.golemLoot],
    tags: ['golem'],
    levelOverrides: [
      {
        minLevel: 61,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 1 } },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
  },
  robotNo1: {
    id: 'robotNo1',
    name: 'Y5-Sentry',
    spineAssetKey: 'robot_no1',
    damageType: 'lightning',
    baseHp: 9.45,
    hpGrowth: 1.62,
    baseDamage: 12,
    damageGrowth: 0.94,
    baseDefense: 4.5,
    defenseGrowth: 1.5,
    speed: 10,
    crit: 0,
    dodge: 0,
    lightningResist: 0.2,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo2: {
    id: 'robotNo2',
    name: 'KRG-01',
    spineAssetKey: 'robot_no2',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.62,
    baseDamage: 15,
    damageGrowth: 1.38,
    baseDefense: 6,
    defenseGrowth: 1.5,
    speed: 9,
    crit: 0,
    dodge: 0,
    fireResist: 0.2,
    iceResist: 0.2,
    shadowResist: 0.2,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo3: {
    id: 'robotNo3',
    name: 'Gen5-HVY',
    spineAssetKey: 'robot_no3',
    damageType: 'physical',
    baseHp: 11.7,
    hpGrowth: 1.69,
    baseDamage: 25,
    damageGrowth: 1.38,
    baseDefense: 5.25,
    defenseGrowth: 1.5,
    speed: 6,
    crit: 0.03,
    dodge: 0,
    shadowResist: 0.2,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo4: {
    id: 'robotNo4',
    name: 'Medibot-Mark IV',
    spineAssetKey: 'robot_no4',
    damageType: 'ice',
    baseHp: 11.7,
    hpGrowth: 2.03,
    baseDamage: 15,
    damageGrowth: 0.94,
    baseDefense: 6,
    defenseGrowth: 1.38,
    speed: 10,
    crit: 0,
    dodge: 0.03,
    fireResist: -0.3,
    iceResist: 0.3,
    lightningResist: -0.3,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotNo5: {
    id: 'robotNo5',
    name: 'WasteLogic LX-9',
    spineAssetKey: 'robot_no5',
    damageType: 'fire',
    baseHp: 12.15,
    hpGrowth: 2.03,
    baseDamage: 12.5,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 1.5,
    speed: 7,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lootTables: [et.robotLoot],
    tags: ['robot'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          {
            id: 'PoisonOnAttackScaled',
            params: { scalePercent: 0.2, applyChance: 0.4 },
          },
        ],
      },
    ],
  },
  robotNo5Lucky: {
    id: 'robotNo5Lucky',
    name: 'Loaded Robot 5',
    spineAssetKey: 'robot_no5',
    damageType: 'fire',
    baseHp: 12.15,
    hpGrowth: 2.03,
    baseDamage: 12.5,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 1.5,
    speed: 7,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lootTables: [et.robotLuckyLoot],
    tags: ['robot'],
    levelOverrides: [
      {
        minLevel: 121,
        abilities: [
          {
            id: 'PoisonOnAttackScaled',
            params: { scalePercent: 0.2, applyChance: 0.4 },
          },
        ],
      },
    ],
  },
  robotNo6: {
    id: 'robotNo6',
    name: 'BRX-7 Sentry Chassis',
    spineAssetKey: 'robot_no6',
    damageType: 'fire',
    baseHp: 67.5,
    hpGrowth: 7.09,
    baseDamage: 35,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 5,
    speed: 9,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.5,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.robotNo6BossLoot],
    abilities: [{ id: 'BossBrain_RobotNo6' }],
    tags: ['boss', 'robot'],
    spineScale: 0.33,
  },
  robotNo7: {
    id: 'robotNo7',
    name: 'Minifax Model B',
    spineAssetKey: 'robot_no7',
    damageType: 'physical',
    baseHp: 9.9,
    hpGrowth: 1.49,
    baseDamage: 23.76,
    damageGrowth: 1.38,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 8,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.3,
    lightningResist: -0.3,
    lootTables: [et.robotLoot],
    tags: ['robot'],
  },
  robotBoss: {
    id: 'robotBoss',
    name: 'Slumbering Guardian-X5',
    spineAssetKey: 'robot_boss',
    damageType: 'lightning',
    baseHp: 112.5,
    hpGrowth: 8.78,
    baseDamage: 45,
    damageGrowth: 1,
    baseDefense: 9,
    defenseGrowth: 5,
    speed: 8,
    crit: 0.04,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.3,
    lootTables: [et.robotBossBossLoot],
    abilities: [{ id: 'BossBrain_RobotBoss' }],
    tags: ['boss', 'robot'],
    spineScale: 0.22,
  },
  corruptedSkeleton: {
    id: 'corruptedSkeleton',
    name: 'Corrupted Warrior Skeleton',
    spineAssetKey: 'corrupted_skeleton',
    damageType: 'physical',
    baseHp: 10.8,
    hpGrowth: 1.48,
    baseDamage: 13.76,
    damageGrowth: 1.38,
    baseDefense: 3,
    defenseGrowth: 1.31,
    speed: 10,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  corruptedSkelNoHead: {
    id: 'corruptedSkelNoHead',
    name: 'Corrupted Headless Skeleton',
    spineAssetKey: 'corrupted_skel_noHead',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.31,
    speed: 9,
    crit: 0,
    dodge: 0.03,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    abilities: [
      { id: 'DefaultAttack', params: { weight: 1 } },
      { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
    ],
    tags: ['skeleton'],
  },
  corruptedSkel2Axe: {
    id: 'corruptedSkel2Axe',
    name: 'Corrupted Barbarian Skeleton',
    spineAssetKey: 'corrupted_skel_2Axe',
    damageType: 'physical',
    baseHp: 15.3,
    hpGrowth: 2.03,
    baseDamage: 22.5,
    damageGrowth: 1.88,
    baseDefense: 6.75,
    defenseGrowth: 1.44,
    speed: 8,
    crit: 0,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    lightningResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    tags: ['skeleton', 'armed'],
  },
  corruptedSkelWizard: {
    id: 'corruptedSkelWizard',
    name: 'Corrupted Skeleton Wizard',
    spineAssetKey: 'corrupted_skel_wizard',
    damageType: 'physical',
    baseHp: 13.5,
    hpGrowth: 1.48,
    baseDamage: 15,
    damageGrowth: 1.5,
    baseDefense: 3.75,
    defenseGrowth: 1.31,
    speed: 6,
    crit: 0.03,
    dodge: 0,
    fireResist: 0.3,
    iceResist: -0.2,
    shadowResist: 0.3,
    lootTables: [et.skeletonLoot],
    abilities: [
      { id: 'DefaultAttack', params: { weight: 1 } },
      { id: 'CastSilence', params: { weight: 1, recastChance: 0 } },
    ],
    tags: ['skeleton'],
  },
  corruptedSkelAssassin: {
    id: 'corruptedSkelAssassin',
    name: 'Corrupted Skeleton Assassin',
    spineAssetKey: 'corrupted_skel_assassin',
    damageType: 'physical',
    baseHp: 14.4,
    hpGrowth: 1.48,
    baseDamage: 23.76,
    damageGrowth: 1.5,
    baseDefense: 4.5,
    defenseGrowth: 1.25,
    speed: 13,
    crit: 0,
    dodge: 0.03,
    lightningResist: -0.2,
    lootTables: [et.skeletonLoot],
    abilities: [
      {
        id: 'PoisonOnAttackScaled',
        params: { scalePercent: 0.15, applyChance: 0.7 },
      },
    ],
    tags: ['skeleton', 'armed'],
  },
  evilBook: {
    id: 'evilBook',
    name: 'Grouchy Grimoire',
    spineAssetKey: 'EvilBook',
    damageType: 'shadow',
    baseHp: 35,
    hpGrowth: 4,
    baseDamage: 38,
    damageGrowth: 3.3,
    baseDefense: 12,
    defenseGrowth: 3.5,
    speed: 11,
    crit: 0,
    dodge: 0.08,
    shadowResist: 0.3,
    fireResist: -0.2,
    lootTables: [et.evilBookEliteLoot],
    abilities: [
      { id: 'DefaultAttack', params: { weight: 6 } },
      { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
      {
        id: 'CastVulnerable',
        params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
      },
    ],
    levelOverrides: [
      {
        minLevel: 41,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 5 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
          { id: 'CastSilence', params: { weight: 1, recastChance: 0 } },
        ],
      },
      {
        minLevel: 81,
        abilities: [
          { id: 'DefaultAttack', params: { weight: 5 } },
          {
            id: 'CastVulnerable',
            params: { weight: 1, defenseReduction: 0.5, recastChance: 0 },
          },
          { id: 'CastWeak', params: { weight: 1, recastChance: 0 } },
          { id: 'CastSilence', params: { weight: 1, recastChance: 0 } },
          { id: 'CastHypnotize', params: { weight: 1, recastChance: 0 } },
        ],
      },
    ],
    tags: ['dark', 'elite'],
  },
}
