export const foods = {
  'Bacon_Cooked.png': [
    { id: 'EssenceCrunchy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Beef_Grilled.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'Bobba_Green.png': [
    { id: 'EssenceChewy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'Bread_Herbs.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Bread_Rye.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'Bread_Wheat.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceFluffy', quantity: 2 },
  ],
  'Burger.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'CakeBar_Pink.png': [
    { id: 'EssenceDecadent', quantity: 2 },
    { id: 'EssenceFluffy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'CakeSlice_Chokolate.png': [
    { id: 'EssenceDecadent', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceFluffy', quantity: 1 },
  ],
  'CakeSlice_Macha.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceFluffy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'CakeSlice_Regular.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Cheese_Blue.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Cheese_Brie.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'Cheese_Cheddar.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Cheese_Edam.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceHearty', quantity: 1 },
  ],
  'Cheese_Gouda.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Cheese_Swiss.png': [
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Cocktail_Martini.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Cocktail_Red.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Coffee.png': [
    { id: 'EssenceSpicy', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Cookie_Dark.png': [
    { id: 'EssenceCrunchy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'Cookie_White.png': [
    { id: 'EssenceCrunchy', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Crepe_Chokolate.png': [
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'Croissant.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceCrunchy', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'CupCake_Brown.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'CupCake_White.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'Curry_Spicy.png': [
    { id: 'EssenceSpicy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Curry_Yellow.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'Doughnut_Chokolate.png': [
    { id: 'EssenceDecadent', quantity: 2 },
    { id: 'EssenceFluffy', quantity: 1 },
    { id: 'EssenceCrunchy', quantity: 1 },
  ],
  'Doughnut_Pink.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Drink_Brown.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Drink_Lemonade.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 2 },
  ],
  'Drink_Light.png': [
    { id: 'EssenceFresh', quantity: 3 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Drink_Syrup.png': [
    { id: 'EssenceDecadent', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Dumplings.png': [
    { id: 'EssenceChewy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Egg.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Empanada.png': [
    { id: 'EssenceCrunchy', quantity: 1 },
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Fish_Blue.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Fish_Silver.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 2 },
  ],
  'Fries.png': [
    { id: 'EssenceCrunchy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'GameMeat.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'GrilledCheese.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceCrunchy', quantity: 1 },
    { id: 'EssenceHearty', quantity: 1 },
  ],
  'Gyro.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'HotCocoa.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'HotDog.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'IceCream_ChokolateCaramel.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'IceCream_PistachioLemon.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'IceCream_VanillaStrawberry.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Lasagna.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Leg.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 2 },
  ],
  'Lobster_Cooked.png': [
    { id: 'EssenceChewy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'Lobster_Raw.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'Milkshake_Chokolate.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'Milkshake_Strawberry.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'Octopus.png': [
    { id: 'EssenceChewy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 2 },
  ],
  'Onigiri_Pork.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Onigiri_Tuna.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'OpenSandwich_Fish.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceHearty', quantity: 1 },
  ],
  'OpenSandwich_Meat.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Oysters.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Pancakes.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Pie_Blackberry.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceCrunchy', quantity: 1 },
  ],
  'Pie_Cherry.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFluffy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Pie_Cream.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'Pizza_Mushroom.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Pizza_Peperoni.png': [
    { id: 'EssenceSpicy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'PlumCake_Lemon.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'PlumCake_Orange.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'PlumCake_Vanilla.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'PorkChop_Fried.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceCrunchy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'Pudding_Cacao.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'Pudding_Caramel.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Pudding_Pink.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Ramen.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'RareFood_Blue.png': [
    { id: 'EssenceDecadent', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'RareFood_MultiColor.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'RareFood_Pink.png': [
    { id: 'EssenceFluffy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 2 },
  ],
  'RareFood_Yellow.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Ribs.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'RiceOmlete.png': [
    { id: 'EssenceCreamy', quantity: 1 },
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'RottenFood.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'Roulade_Cream.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceFluffy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Salat.png': [
    { id: 'EssenceFresh', quantity: 3 },
    { id: 'EssenceTangy', quantity: 1 },
  ],
  'Sandwich_Advocado.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceHearty', quantity: 1 },
  ],
  'Sandwich_Salami.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'Sausage.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Shripm.png': [
    { id: 'EssenceChewy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 2 },
  ],
  'Skewer_Beef.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Skewer_Pork.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'Soda_Green.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Soda_Red.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceFresh', quantity: 1 },
  ],
  'Soup_Asparagus.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceHearty', quantity: 1 },
  ],
  'Soup_Spinach.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'Soup_Tomato.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'Spaghetti_Cream.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Spaghetti_Marinara.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Stew_Beef.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Stew_Cream.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Stew_Paprika.png': [
    { id: 'EssenceSpicy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 2 },
  ],
  'Sushi.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceCreamy', quantity: 1 },
  ],
  'Taco.png': [
    { id: 'EssenceHearty', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceCrunchy', quantity: 1 },
  ],
  'Takoyaki.png': [
    { id: 'EssenceChewy', quantity: 2 },
    { id: 'EssenceSpicy', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'Tart_BlackCurrant.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceCrunchy', quantity: 1 },
  ],
  'Tart_RedCurrant.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceCrunchy', quantity: 1 },
  ],
  'Tea.png': [
    { id: 'EssenceFresh', quantity: 2 },
    { id: 'EssenceTangy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Wine_Red.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceDecadent', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
  'Wine_White.png': [
    { id: 'EssenceTangy', quantity: 2 },
    { id: 'EssenceFresh', quantity: 1 },
    { id: 'EssenceDecadent', quantity: 1 },
  ],
  'khachapuri.png': [
    { id: 'EssenceCreamy', quantity: 2 },
    { id: 'EssenceHearty', quantity: 1 },
    { id: 'EssenceChewy', quantity: 1 },
  ],
  'mooncake.png': [
    { id: 'EssenceDecadent', quantity: 2 },
    { id: 'EssenceChewy', quantity: 1 },
    { id: 'EssenceSpicy', quantity: 1 },
  ],
}

export const foodNames = {
  'Bacon_Cooked.png': [
    'Crispy Bacon Strips',
    'Maple-Glazed Bacon',
    'Thick-Cut Smoked Bacon',
    'Breakfast Bacon Rashers',
    'Candied Bacon Twists',
  ],
  'Beef_Grilled.png': [
    'Grilled Ribeye Steak',
    'Charred Beef Medallions',
    'Blackened Sirloin Tips',
    'Flame-Seared Skirt Steak',
    'Beef Bulgogi Skewers',
  ],
  'Bobba_Green.png': [
    'Matcha Bubble Tea',
    'Green Tea Boba',
    'Honeydew Boba Smoothie',
    'Jasmine Milk Tea with Tapioca',
    'Avocado Boba Shake',
  ],
  'Bread_Herbs.png': [
    'Rosemary Focaccia',
    'Herbed Flatbread',
    'Garlic & Chive Loaf',
    'Basil Infused Baguette',
    'Savory Garden Bread',
  ],
  'Bread_Rye.png': [
    'Classic Rye Loaf',
    'Seeded Caraway Rye',
    'Dark Pumpernickel Bread',
    'Scandinavian Rye Slices',
    'Baltic Black Bread',
  ],
  'Bread_Wheat.png': [
    'Whole Wheat Sandwich Bread',
    'Honey Wheat Loaf',
    'Country Farmhouse Bread',
    'Rustic Whole Grain Boule',
    'Cracked Wheat Artisan Bread',
  ],
  'Burger.png': [
    'Classic Cheeseburger',
    'Double Bacon Burger',
    'BBQ Pulled Pork Burger',
    'Portobello Veggie Burger',
    'Wagyu Smash Burger',
  ],
  'CakeBar_Pink.png': [
    'Strawberry Cake Bar',
    'Raspberry Cream Slice',
    'Pink Velvet Bar',
    'Cherry Shortcake Bar',
    'Guava Glazed Cake Stick',
  ],
  'CakeSlice_Chokolate.png': [
    'Dark Chocolate Ganache Cake',
    'Triple Fudge Cake Slice',
    'Black Forest Cake',
    'Chocolate Lava Cake Slice',
    'Nutella Layer Cake',
  ],
  'CakeSlice_Macha.png': [
    'Matcha Green Tea Cake',
    'Jade Layer Cheesecake',
    'Pistachio Matcha Slice',
    'Green Tea Opera Cake',
    'Spinach Infused Cake Slice',
  ],
  'CakeSlice_Regular.png': [
    'Vanilla Sponge Cake',
    'Buttercream Celebration Slice',
    'Classic Birthday Cake',
    'Lemon Chiffon Slice',
    'Almond Butter Cake',
  ],
  'Cheese_Blue.png': [
    'Blue Stilton Wedge',
    'Gorgonzola Crumble',
    'Roquefort Slice',
    'Mold-Ripened Blue Cheese',
    "Bleu d'Auvergne",
  ],
  'Cheese_Brie.png': [
    'Creamy Brie Wheel',
    'Triple Cream Brie',
    'Brie en Croûte',
    'French Soft Cheese Wedge',
    'Camembert Style Round',
  ],
  'Cheese_Cheddar.png': [
    'Aged Cheddar Block',
    'Sharp White Cheddar',
    'Smoked Farmhouse Cheddar',
    'English Mature Cheddar',
    'Vermont Cheddar Slice',
  ],
  'Cheese_Edam.png': [
    'Classic Edam Ball',
    'Young Edam Wedge',
    'Dutch Semi-Hard Cheese',
    'Red Wax Edam',
    'Mild Picnic Cheese',
  ],
  'Cheese_Gouda.png': [
    'Aged Gouda Wheel',
    'Smoked Gouda Wedge',
    'Creamy Young Gouda',
    'Dutch Market Cheese',
    'Caramelized Gouda Slice',
  ],
  'Cheese_Swiss.png': [
    'Emmental Swiss Cheese',
    'Jarlsberg Slice',
    'Hole-Riddled Swiss Block',
    'Baby Swiss Wedge',
    'Alpine Fondue Cheese',
  ],
  'Cocktail_Martini.png': [
    'Classic Dry Martini',
    'Olive Garnished Martini',
    'Lemon Twist Martini',
    'Dirty Gin Martini',
    'Vodka Vermouth Cocktail',
  ],
  'Cocktail_Red.png': [
    'Cranberry Cosmopolitan',
    'Blood Orange Negroni',
    'Pomegranate Margarita',
    'Cherry Manhattan',
    'Hibiscus Rum Punch',
  ],
  'Coffee.png': [
    'Espresso Shot',
    'Cappuccino with Foam Art',
    'Latte Macchiato',
    'Iced Americano',
    'Flat White',
  ],
  'Cookie_Dark.png': [
    'Double Chocolate Chip Cookie',
    'Espresso Cocoa Cookie',
    'Molasses Spice Cookie',
    'Blackout Brownie Cookie',
    'Charcoal Sesame Biscuit',
  ],
  'Cookie_White.png': [
    'White Chocolate Macadamia Cookie',
    'Vanilla Sugar Cookie',
    'Butter Shortbread Round',
    'Coconut Snowball Cookie',
    'Lemon Drizzle Cookie',
  ],
  'Crepe_Chokolate.png': [
    'Chocolate Hazelnut Crepe',
    'Nutella Strawberry Folded Crepe',
    'Cacao Drizzle French Crepe',
    'Choco-Banana Pancake Wrap',
    'Mole Sauce Savory Crepe',
  ],
  'Croissant.png': [
    'Buttery French Croissant',
    'Almond Filled Croissant',
    'Chocolate Pain au Chocolat',
    'Savory Ham & Cheese Croissant',
    'Japanese Melon Pan',
  ],
  'CupCake_Brown.png': [
    'Chocolate Fudge Cupcake',
    'Mocha Ganache Cupcake',
    'Hazelnut Cream Cupcake',
    'Peanut Butter Cupcake',
    'Dark Caramel Cupcake',
  ],
  'CupCake_White.png': [
    'Vanilla Bean Cupcake',
    'Lemon Buttercream Cupcake',
    'Coconut Snowflake Cupcake',
    'White Chocolate Raspberry Cupcake',
    'Almond Wedding Cupcake',
  ],
  'Curry_Spicy.png': [
    'Fiery Red Thai Curry',
    'Spicy Vindaloo',
    'Chili Pepper Beef Curry',
    "Devil's Chicken Curry",
    'Sichuan Mala Hotpot',
  ],
  'Curry_Yellow.png': [
    'Golden Yellow Curry',
    'Mild Japanese Katsu Curry',
    'Massaman Curry Bowl',
    'Lemongrass Coconut Curry',
    'Pumpkin Thai Curry',
  ],
  'Doughnut_Chokolate.png': [
    'Chocolate Glazed Doughnut',
    'Double Fudge Ring',
    'Triple Chocolate Donut',
    'Churro Cocoa Twist',
    'Boston Cream Filled Doughnut',
  ],
  'Doughnut_Pink.png': [
    'Strawberry Frosted Donut',
    'Pink Lemonade Ring',
    'Raspberry Glazed Doughnut',
    'Guava Icing Donut',
    'Dragonfruit Sprinkle Donut',
  ],
  'Drink_Brown.png': [
    'Iced Coffee',
    'Cola Float',
    'Root Beer Mug',
    'Caramel Iced Latte',
    'Whiskey Sour',
  ],
  'Drink_Lemonade.png': [
    'Classic Lemonade',
    'Sparkling Citrus Punch',
    'Mint Lemon Refresher',
    'Yuzu Lemon Soda',
    'Limoncello Cooler',
  ],
  'Drink_Light.png': [
    'Coconut Water',
    'Lychee Sparkler',
    'Pear Cider',
    'Vanilla Cream Soda',
    'Pineapple Agua Fresca',
  ],
  'Drink_Syrup.png': [
    'Maple Syrup Shot',
    'Honey Mead Glass',
    'Molasses Rum Cocktail',
    'Caramel Drizzle Latte',
    'Sorghum Sweet Tea',
  ],
  'Dumplings.png': [
    'Pork Gyoza',
    'Shrimp Har Gow',
    'Chicken Potstickers',
    'Soup Dumpling (Xiao Long Bao)',
    'Pierogi with Sour Cream',
  ],
  'Egg.png': [
    'Sunny Side Up Egg',
    'Poached Breakfast Egg',
    'Soft Boiled Ramen Egg',
    'Scotch Egg',
    'Salted Duck Egg',
  ],
  'Empanada.png': [
    'Chicken Empanada',
    'Spicy Beef Turnover',
    'Cheesy Chorizo Empanada',
    'Cornish Pasty',
    'Mini Calzone Pocket',
  ],
  'Fish_Blue.png': [
    'Bluefin Tuna Cut',
    'Butterfly Blue Mackerel',
    'Pacific Snapper',
    'Swordfish Steak',
    'Fantasy Bluefish Fillet',
  ],
  'Fish_Silver.png': [
    'Silver Anchovy Filets',
    'Atlantic Herring',
    'Shiny Sardine Stack',
    'Mackerel Cutlet',
    'Smoked Smelt',
  ],
  'Fries.png': [
    'Crispy French Fries',
    'Truffle Parmesan Fries',
    'Sweet Potato Wedges',
    'Belgian Frites with Aioli',
    'Tempura Fried Lotus Root',
  ],
  'GameMeat.png': [
    'Venison Steak',
    'Wild Boar Roast',
    'Elk Tenderloin',
    'Bison Burger Patty',
    'Grilled Ostrich Fillet',
  ],
  'GrilledCheese.png': [
    'Classic Grilled Cheese Sandwich',
    'Three Cheese Melt',
    'Bacon & Cheddar Panini',
    'Brie & Fig Toastie',
    'Croque Monsieur',
  ],
  'Gyro.png': [
    'Lamb Gyro Wrap',
    'Chicken Shawarma',
    'Falafel Pita Pocket',
    'Beef Doner Kebab',
    'Mediterranean Street Wrap',
  ],
  'HotCocoa.png': [
    'Classic Hot Chocolate',
    'Marshmallow Cocoa',
    'Peppermint Mocha',
    'Spiced Aztec Hot Chocolate',
    'Nutella Drinking Chocolate',
  ],
  'HotDog.png': [
    'Classic Beef Hot Dog',
    'Chili Cheese Dog',
    'Chicago Style Hot Dog',
    'Bacon Wrapped Danger Dog',
    'Japanese Terimayo Dog',
  ],
  'IceCream_ChokolateCaramel.png': [
    'Chocolate Caramel Sundae',
    'Double Fudge Ripple Cone',
    'Salted Caramel Gelato',
    'Chocolate Turtle Ice Cream',
    'Mocha Almond Fudge',
  ],
  'IceCream_PistachioLemon.png': [
    'Pistachio Lemon Sorbet',
    'Lemon Pistachio Swirl',
    'Citrus Nut Gelato',
    'Yuzu Pistachio Scoop',
    'Lemon Almond Crunch',
  ],
  'IceCream_VanillaStrawberry.png': [
    'Vanilla Strawberry Swirl',
    'Strawberry Shortcake Ice Cream',
    'Vanilla Bean & Berry Gelato',
    'Strawberry Cheesecake Scoop',
    'Triple Berry Vanilla Delight',
  ],
  'Lasagna.png': [
    'Classic Beef Lasagna',
    'Spinach Ricotta Lasagna',
    'Mushroom Alfredo Lasagna',
    'Sausage Layered Lasagna',
    'Eggplant Parmesan Bake',
  ],
  'Leg.png': [
    'Roasted Turkey Leg',
    'BBQ Chicken Drumstick',
    'Smoked Ham Shank',
    'Slow Cooked Lamb Shank',
    'Crispy Duck Leg Confit',
  ],
  'Lobster_Cooked.png': [
    'Steamed Whole Lobster',
    'Butter Poached Lobster Tail',
    'Grilled Lobster with Herbs',
    'Lobster Thermidor',
    'Lobster Newberg',
  ],
  'Lobster_Raw.png': [
    'Fresh Raw Lobster',
    'Live Market Lobster',
    'Raw Lobster Tail',
    'Sashimi Grade Lobster',
    'Uncooked Spiny Lobster',
  ],
  'Milkshake_Chokolate.png': [
    'Classic Chocolate Milkshake',
    'Double Fudge Shake',
    'Chocolate Peanut Butter Shake',
    'Mocha Espresso Milkshake',
    'Triple Chocolate Malt',
  ],
  'Milkshake_Strawberry.png': [
    'Strawberry Cream Milkshake',
    'Berry Blast Smoothie',
    'Vanilla Strawberry Swirl Shake',
    'Wild Strawberry Malt',
    'Strawberry Cheesecake Shake',
  ],
  'Octopus.png': [
    'Grilled Octopus Tentacle',
    'Takoyaki Filling',
    'Marinated Octopus Salad',
    'Galician Pulpo a la Feira',
    'Octopus Carpaccio',
  ],
  'Onigiri_Pork.png': [
    'Pork Onigiri Rice Ball',
    'Braised Pork Belly Onigiri',
    'Teriyaki Pork Stuffed Rice Ball',
    'Char Siu Onigiri',
    'Grilled Pork Yaki-Onigiri',
  ],
  'Onigiri_Tuna.png': [
    'Tuna Mayo Onigiri',
    'Seared Tuna Rice Ball',
    'Spicy Tuna Onigiri',
    'Ahi Poke Stuffed Rice Ball',
    'Wasabi Tuna Onigiri',
  ],
  'OpenSandwich_Fish.png': [
    'Smoked Salmon Open Sandwich',
    'Herring Toast',
    'Tuna Nicoise Tartine',
    'Mackerel Rye Toast',
    'Sardine Avocado Open Sandwich',
  ],
  'OpenSandwich_Meat.png': [
    'Roast Beef Open Sandwich',
    'Pastrami Rye Tartine',
    'Turkey Cranberry Open Face',
    'Ham and Brie Toast',
    'Pulled Pork Open Sandwich',
  ],
  'Oysters.png': [
    'Fresh Raw Oysters',
    'Grilled Oysters Rockefeller',
    'Oysters on the Half Shell',
    'Tempura Fried Oysters',
    'Garlic Butter Baked Oysters',
  ],
  'Pancakes.png': [
    'Buttermilk Pancakes',
    'Blueberry Pancake Stack',
    'Banana Walnut Pancakes',
    'Chocolate Chip Pancakes',
    'Japanese Souffle Pancakes',
  ],
  'Pie_Blackberry.png': [
    'Blackberry Lattice Pie',
    'Wild Berry Crumble Pie',
    'Blackberry Lemon Tart',
    'Blackberry Custard Pie',
    'Mixed Forest Berry Pie',
  ],
  'Pie_Cherry.png': [
    'Classic Cherry Pie',
    'Sour Cherry Streusel Pie',
    'Cherry Almond Tart',
    'Cherry Chocolate Pie',
    'Sweet Cherry Cobbler',
  ],
  'Pie_Cream.png': [
    'Banana Custard Pie',
    'Coconut Custard Pie',
    'Chocolate Custard Pie',
    'Strawberries & Custard Pie',
    'Peanut Butter Pie',
  ],
  'Pizza_Mushroom.png': [
    'Wild Mushroom Pizza',
    'Truffle Mushroom Flatbread',
    'Portobello Spinach Pizza',
    'Forest Blend Fungi Pizza',
    'Mushroom White Sauce Pizza',
  ],
  'Pizza_Peperoni.png': [
    'Classic Pepperoni Pizza',
    'Double Meat Pepperoni Pie',
    'Spicy Salami Flatbread',
    'Pepperoni & Olive Deep Dish',
    'Crispy Thin Crust Pepperoni',
  ],
  'PlumCake_Lemon.png': [
    'Lemon Plum Tea Cake',
    'Citrus Plum Loaf',
    'Lemon-Glazed Plum Cake',
    'Almond Lemon Plum Pound Cake',
    'Plum Citrus Sponge',
  ],
  'PlumCake_Orange.png': [
    'Orange Plum Bundt Cake',
    'Plum Marmalade Cake',
    'Blood Orange Plum Tart',
    'Spiced Orange Plum Loaf',
    'Caramelized Plum Citrus Cake',
  ],
  'PlumCake_Vanilla.png': [
    'Vanilla Plum Butter Cake',
    'Plum Cream Pound Cake',
    'Vanilla Bean Plum Loaf',
    'Plum Custard Cake',
    'Simple Plum Vanilla Tart',
  ],
  'PorkChop_Fried.png': [
    'Fried Pork Chop',
    'Breaded Schnitzel Cutlet',
    'Katsu Pork Chop',
    'Southern Fried Pork Steak',
    'Pan Fried Bone-In Pork Chop',
  ],
  'Pudding_Cacao.png': [
    'Chocolate Pudding',
    'Dark Cocoa Pots de Crème',
    'Bittersweet Chocolate Custard',
    'Belgian Chocolate Pudding Cup',
    'Cacao Flan',
  ],
  'Pudding_Caramel.png': [
    'Caramel Flan',
    'Crème Caramel',
    'Salted Caramel Custard',
    'Burnt Sugar Pudding',
    'Sticky Toffee Pudding',
  ],
  'Pudding_Pink.png': [
    'Strawberry Mousse Pudding',
    'Raspberry Cream Flan',
    'Cherry Blossom Custard',
    'Rosewater Panna Cotta',
    'Pink Dragonfruit Pudding',
  ],
  'Ramen.png': [
    'Tonkotsu Pork Ramen',
    'Shoyu Chicken Ramen',
    'Miso Seafood Ramen',
    'Spicy Tantanmen',
    'Vegan Mushroom Ramen',
  ],
  'RareFood_Blue.png': [
    'Blue Starfruit Tart',
    'Mystic Berry Gelée',
    'Cobalt Jelly Slice',
    'Sapphire Crystal Pudding',
    'Frozen Blue Lotus Cake',
  ],
  'RareFood_MultiColor.png': [
    'Rainbow Sushi Roll',
    'Confetti Fruit Parfait',
    'Spectrum Macaron Tower',
    'Galactic Layer Cake',
    'Aurora Fruit Sorbet',
  ],
  'RareFood_Pink.png': [
    'Blush Rose Gelatin',
    'Pink Pearl Mousse',
    'Cotton Candy Cheesecake',
    'Lychee Blossom Tart',
    'Cherry Cream Bombe',
  ],
  'RareFood_Yellow.png': [
    'Golden Mango Custard',
    'Lemon Star Pudding',
    'Banana Cream Soufflé',
    'Sunlight Honey Tart',
    'Pineapple Citrus Dome',
  ],
  'Ribs.png': [
    'BBQ Baby Back Ribs',
    'Smoked Pork Ribs',
    'Sticky Asian Spare Ribs',
    'Honey Glazed Rib Rack',
    'Memphis Dry Rub Ribs',
  ],
  'RiceOmlete.png': [
    'Japanese Omurice',
    'Cheesy Rice Omelette',
    'Two Egg Omelette',
    'Classic Omelet',
    'Mushroom Gravy Omurice',
  ],
  'RottenFood.png': [
    'Moldy Bread',
    'Spoiled Meat',
    'Sour Milk Curd',
    'Rotten Fruit Medley',
    'Fermented Swamp Stew',
  ],
  'Roulade_Cream.png': [
    'Vanilla Cream Roulade',
    'Chocolate Swiss Roll',
    'Berry Jam Roll Cake',
    'Lemon Curd Roulade',
    'Green Tea Matcha Roll',
  ],
  'Salat.png': [
    'Caesar Salad',
    'Garden Vegetable Salad',
    'Greek Feta Salad',
    'Spinach Strawberry Salad',
    'Asian Sesame Slaw',
  ],
  'Sandwich_Advocado.png': [
    'Avocado Toast Sandwich',
    'Egg & Avocado Melt',
    'BLT with Avocado',
    'Smoked Salmon Avocado Stack',
    'Chicken Avocado Club',
  ],
  'Sandwich_Salami.png': [
    'Salami Submarine',
    'Italian Salami Panini',
    'Pepperoni Melt Sandwich',
    'Salami and Provolone Hoagie',
    'Spicy Salami Baguette',
  ],
  'Sausage.png': [
    'Grilled Bratwurst',
    'Smoked Kielbasa',
    'Italian Spicy Sausage',
    'Breakfast Pork Links',
    'Andouille Cajun Sausage',
  ],
  'Shripm.png': [
    'Grilled Garlic Shrimp',
    'Tempura Fried Shrimp',
    'Lemon Butter Prawns',
    'Shrimp Scampi',
    'Coconut Fried Shrimp',
  ],
  'Skewer_Beef.png': [
    'Beef Yakitori Skewer',
    'Korean Bulgogi Skewers',
    'Spiced Beef Kebab',
    'Pepper Steak Skewer',
    'Chimichurri Beef Stick',
  ],
  'Skewer_Pork.png': [
    'Pork Satay Skewer',
    'Teriyaki Pork Yakitori',
    'Herb Grilled Pork Stick',
    'Spicy Glazed Pork Skewer',
    'Sweet & Sour Pork Skewer',
  ],
  'Soda_Green.png': [
    'Melon Cream Soda',
    'Lime Sparkling Water',
    'Green Apple Fizz',
    'Cucumber Mint Cooler',
    'Yuzu Lime Soda',
  ],
  'Soda_Red.png': [
    'Cherry Cola',
    'Strawberry Cream Soda',
    'Pomegranate Sparkler',
    'Red Raspberry Fizz',
    'Blood Orange Soda',
  ],
  'Soup_Asparagus.png': [
    'Cream of Asparagus Soup',
    'Chilled Asparagus Vichyssoise',
    'Asparagus Leek Bisque',
    'Herb Roasted Asparagus Soup',
    'Asparagus and Pea Velouté',
  ],
  'Soup_Spinach.png': [
    'Spinach Parmesan Soup',
    'Creamy Spinach Bisque',
    'Spinach & Artichoke Chowder',
    'Garlic Spinach Broth',
    'Wilted Spinach Consommé',
  ],
  'Soup_Tomato.png': [
    'Classic Tomato Soup',
    'Roasted Tomato Basil Soup',
    'Tomato Bisque with Croutons',
    'Spicy Tomato Gazpacho',
    'Sun-Dried Tomato Chowder',
  ],
  'Spaghetti_Cream.png': [
    'Creamy Alfredo Spaghetti',
    'Carbonara Pasta',
    'Garlic Parmesan Spaghetti',
    'Truffle Cream Linguine',
    'Mushroom Cream Pasta',
  ],
  'Spaghetti_Marinara.png': [
    'Classic Spaghetti Marinara',
    'Meatball Spaghetti',
    'Seafood Marinara Pasta',
    'Sausage Ragu Spaghetti',
    'Spicy Arrabbiata Pasta',
  ],
  'Stew_Beef.png': [
    'Beef Bourguignon',
    'Hearty Beef Stew',
    'Guinness Braised Beef',
    'Hungarian Goulash',
    'Slow Cooker Pot Roast',
  ],
  'Stew_Cream.png': [
    'Chicken Cream Stew',
    'Seafood Chowder',
    'Creamy Turkey Stew',
    'White Wine Cream Stew',
    'Salmon Dill Cream Stew',
  ],
  'Stew_Paprika.png': [
    'Paprika Chicken Stew',
    'Hungarian Paprikash',
    'Paprika Beef Stroganoff',
    'Spicy Sausage Paprika Stew',
    'Paprika Lentil Soup',
  ],
  'Sushi.png': [
    'Tuna Nigiri',
    'Salmon Sashimi',
    'Dragon Roll',
    'California Roll',
    'Unagi Eel Roll',
  ],
  'Taco.png': [
    'Beef Soft Taco',
    'Carnitas Street Taco',
    'Baja Fish Taco',
    'Chicken Tinga Taco',
    'Vegetarian Black Bean Taco',
  ],
  'Takoyaki.png': [
    'Classic Takoyaki Balls',
    'Spicy Mayo Takoyaki',
    'Wasabi Octopus Balls',
    'Teriyaki Takoyaki',
    'Cheese Stuffed Takoyaki',
  ],
  'Tart_BlackCurrant.png': [
    'Blackcurrant Almond Tart',
    'Glazed Cassis Tart',
    'Blackcurrant Chocolate Tart',
    'Forest Berry Custard Tart',
    'Lemon Blackcurrant Tart',
  ],
  'Tart_RedCurrant.png': [
    'Redcurrant Meringue Tart',
    'Sweet Redcurrant Cheesecake',
    'Currant & Rosewater Tart',
    'Redcurrant Almond Frangipane',
    'Spiced Redcurrant Pie',
  ],
  'Tea.png': [
    'Jasmine Green Tea',
    'Earl Grey Brew',
    'Chamomile Herbal Tea',
    'Matcha Latte',
    'English Breakfast Tea',
  ],
  'Wine_Red.png': [
    'Cabernet Sauvignon',
    'Merlot Reserve',
    'Pinot Noir Glass',
    'Zinfandel Red',
    'Malbec Vintage',
  ],
  'Wine_White.png': [
    'Chardonnay Classic',
    'Sauvignon Blanc',
    'Pinot Grigio',
    'Riesling Sweet White',
    'Viognier White Wine',
  ],
  'khachapuri.png': [
    'Georgian Khachapuri',
    'Cheese Stuffed Bread Boat',
    'Egg & Cheese Khachapuri',
    'Adjarian Khachapuri',
    'Savory Cheese Flatbread',
  ],
  'mooncake.png': [
    'Lotus Seed Mooncake',
    'Red Bean Mooncake',
    'Egg Yolk Snow Skin Mooncake',
    'Pandan Custard Mooncake',
    'Matcha Green Tea Mooncake',
  ],
}
