export const Z0 = {
    outer_temple: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 20,
          items: [
            { id: 'skeleton', weight: 30 },
            { id: 'skelAssassin', weight: 30 },
            { id: 'darkShaman', weight: 20 },
            { id: 'mushroomSoldier', weight: 20 },
            { id: 'slimeKnight', weight: 6 },
            { id: 'slimeGems', weight: 6 },
            { id: 'skel2Axe', weight: 6 },
            { id: 'skelGreatSword', weight: 6 },
            { id: 'golemMountainLucky', weight: 1 },
            { id: 'slimeBoneLucky', weight: 1 },
            { id: 'mushroomSoldierLucky', weight: 1 },
            { id: 'darkBigGuyLucky', weight: 1 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
        {
          minLevel: 21,
          maxLevel: 40,
          items: [
            { id: 'skeleton', weight: 30 },
            { id: 'skelAssassin', weight: 30 },
            { id: 'darkShaman', weight: 20 },
            { id: 'mushroomSoldier', weight: 20 },
            { id: 'slimeKnight', weight: 6 },
            { id: 'slimeGems', weight: 6 },
            { id: 'skel2Axe', weight: 6 },
            { id: 'skelGreatSword', weight: 6 },
            { id: 'golemMountainLucky', weight: 1 },
            { id: 'slimeBoneLucky', weight: 1 },
            { id: 'mushroomSoldierLucky', weight: 1 },
            { id: 'darkBigGuyLucky', weight: 1 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
        {
          minLevel: 41,
          maxLevel: 60,
          items: [
            { id: 'skeleton', weight: 30 },
            { id: 'skelAssassin', weight: 30 },
            { id: 'darkShaman', weight: 20 },
            { id: 'mushroomSoldier', weight: 20 },
            { id: 'slimeKnight', weight: 6 },
            { id: 'slimeGems', weight: 6 },
            { id: 'skel2Axe', weight: 6 },
            { id: 'skelGreatSword', weight: 6 },
            { id: 'golemMountainLucky', weight: 1 },
            { id: 'slimeBoneLucky', weight: 1 },
            { id: 'mushroomSoldierLucky', weight: 1 },
            { id: 'darkBigGuyLucky', weight: 1 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
        {
          minLevel: 61,
          items: [
            { id: 'skeleton', weight: 30 },
            { id: 'skelAssassin', weight: 30 },
            { id: 'darkShaman', weight: 20 },
            { id: 'mushroomSoldier', weight: 20 },
            { id: 'slimeKnight', weight: 6 },
            { id: 'slimeGems', weight: 6 },
            { id: 'skel2Axe', weight: 6 },
            { id: 'skelGreatSword', weight: 6 },
            { id: 'golemMountainLucky', weight: 1 },
            { id: 'slimeBoneLucky', weight: 1 },
            { id: 'mushroomSoldierLucky', weight: 1 },
            { id: 'darkBigGuyLucky', weight: 1 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
      ],
    },
    seaside_cliffs: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 20,
          items: [
            { id: 'slimeCat', weight: 10 },
            { id: 'slimeBigMouth', weight: 10 },
            { id: 'slimeBone', weight: 5 },
            { id: 'slimeKnight', weight: 5 },
            { id: 'slimeGems', weight: 2 },
          ],
        },
        {
          minLevel: 21,
          maxLevel: 40,
          items: [
            { id: 'slimeCat', weight: 10 },
            { id: 'slimeBigMouth', weight: 10 },
            { id: 'slimeBone', weight: 5 },
            { id: 'slimeKnight', weight: 5 },
            { id: 'slimeGems', weight: 2 },
            { id: 'slimeBoneLucky', weight: 1 },
          ],
        },
        {
          minLevel: 41,
          maxLevel: 60,
          items: [
            { id: 'slimeCat', weight: 7 },
            { id: 'slimeBigMouth', weight: 7 },
            { id: 'slimeBone', weight: 7 },
            { id: 'slimeKnight', weight: 12 },
            { id: 'slimeGems', weight: 12 },
            { id: 'slimeBoneLucky', weight: 1 },
          ],
        },
        {
          minLevel: 61,
          items: [
            { id: 'slimeCat', weight: 4 },
            { id: 'slimeBigMouth', weight: 4 },
            { id: 'slimeBone', weight: 11 },
            { id: 'slimeKnight', weight: 11 },
            { id: 'slimeGems', weight: 13 },
            { id: 'slimeBoneLucky', weight: 1 },
          ],
        },
      ],
    },
    mossy_forest: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 5,
          items: [
            { id: 'darkBat', weight: 10 },
            { id: 'darkHand', weight: 10 },
            { id: 'darkShaman', weight: 5 },
            { id: 'darkWorm', weight: 5 },
            { id: 'darkChild', weight: 2 },
          ],
        },
        {
          minLevel: 6,
          maxLevel: 20,
          items: [
            { id: 'darkBat', weight: 10 },
            { id: 'darkHand', weight: 10 },
            { id: 'darkShaman', weight: 8 },
            { id: 'darkWorm', weight: 8 },
            { id: 'darkChild', weight: 5 },
            { id: 'darkSpider', weight: 5 },
            { id: 'darkBigGuyLucky', weight: 1 },
          ],
        },
        {
          minLevel: 21,
          maxLevel: 40,
          items: [
            { id: 'darkBat', weight: 7 },
            { id: 'darkHand', weight: 7 },
            { id: 'darkShaman', weight: 7 },
            { id: 'darkWorm', weight: 12 },
            { id: 'darkChild', weight: 12 },
            { id: 'darkSpider', weight: 12 },
            { id: 'cannibal', weight: 12 },
            { id: 'darkWizard', weight: 5 },
          ],
        },
        {
          minLevel: 41,
          maxLevel: 60,
          items: [
            { id: 'darkBat', weight: 4 },
            { id: 'darkHand', weight: 4 },
            { id: 'darkShaman', weight: 4 },
            { id: 'darkWorm', weight: 11 },
            { id: 'darkChild', weight: 11 },
            { id: 'darkSpider', weight: 13 },
            { id: 'cannibal', weight: 13 },
            { id: 'darkWizard', weight: 13 },
            { id: 'darkBigGuy', weight: 5 },
            { id: 'darkBigGuyLucky', weight: 1 },
          ],
        },
        {
          minLevel: 61,
          items: [
            { id: 'darkBat', weight: 4 },
            { id: 'darkHand', weight: 4 },
            { id: 'darkShaman', weight: 4 },
            { id: 'darkWorm', weight: 11 },
            { id: 'darkChild', weight: 11 },
            { id: 'darkSpider', weight: 13 },
            { id: 'cannibal', weight: 13 },
            { id: 'darkWizard', weight: 13 },
            { id: 'darkBigGuy', weight: 13 },
            { id: 'darkBigGuyLucky', weight: 1 },
          ],
        },
      ],
    },
    ruined_path: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 20,
          items: [
            { id: 'skeleton', weight: 10 },
            { id: 'skelNoHead', weight: 10 },
            { id: 'skelArcher', weight: 5 },
            { id: 'skelAssassin', weight: 5 },
            { id: 'skelWizard', weight: 2 },
          ],
        },
        {
          minLevel: 21,
          maxLevel: 40,
          items: [
            { id: 'skeleton', weight: 10 },
            { id: 'skelNoHead', weight: 10 },
            { id: 'skelArcher', weight: 10 },
            { id: 'skelAssassin', weight: 10 },
            { id: 'skelWizard', weight: 5 },
            { id: 'skel2Axe', weight: 5 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
        {
          minLevel: 41,
          maxLevel: 60,
          items: [
            { id: 'skeleton', weight: 4 },
            { id: 'skelNoHead', weight: 4 },
            { id: 'skelArcher', weight: 10 },
            { id: 'skelAssassin', weight: 10 },
            { id: 'skelWizard', weight: 13 },
            { id: 'skel2Axe', weight: 13 },
            { id: 'skelGreatSword', weight: 5 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
        {
          minLevel: 61,
          items: [
            { id: 'skeleton', weight: 2 },
            { id: 'skelNoHead', weight: 2 },
            { id: 'skelArcher', weight: 13 },
            { id: 'skelAssassin', weight: 5 },
            { id: 'skelWizard', weight: 5 },
            { id: 'skel2Axe', weight: 13 },
            { id: 'skelGreatSword', weight: 13 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
      ],
    },
    fields: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 5,
          items: [
            { id: 'mushroomChild', weight: 10 },
            { id: 'mushroomSmall', weight: 10 },
            { id: 'mushroomFrog', weight: 8 },
            { id: 'mushroomTeeth', weight: 5 },
          ],
        },
        {
          minLevel: 6,
          maxLevel: 20,
          items: [
            { id: 'mushroomChild', weight: 10 },
            { id: 'mushroomSmall', weight: 10 },
            { id: 'mushroomFrog', weight: 10 },
            { id: 'mushroomTeeth', weight: 10 },
            { id: 'mushroomMonster', weight: 5 },
            { id: 'mushroomSoldierLucky', weight: 1 },
          ],
        },
        {
          minLevel: 21,
          maxLevel: 40,
          items: [
            { id: 'mushroomChild', weight: 7 },
            { id: 'mushroomSmall', weight: 7 },
            { id: 'mushroomFrog', weight: 10 },
            { id: 'mushroomTeeth', weight: 10 },
            { id: 'mushroomMonster', weight: 10 },
            { id: 'mushroomSoldier', weight: 10 },
            { id: 'mushroomSoldierLucky', weight: 1 },
          ],
        },
        {
          minLevel: 41,
          maxLevel: 60,
          items: [
            { id: 'mushroomChild', weight: 4 },
            { id: 'mushroomSmall', weight: 4 },
            { id: 'mushroomFrog', weight: 10 },
            { id: 'mushroomTeeth', weight: 10 },
            { id: 'mushroomMonster', weight: 13 },
            { id: 'mushroomSoldier', weight: 13 },
          ],
        },
        { minLevel: 41, items: [{ id: 'mushroomSoldierLucky', weight: 1 }] },
        {
          minLevel: 61,
          items: [
            { id: 'mushroomChild', weight: 2 },
            { id: 'mushroomSmall', weight: 2 },
            { id: 'mushroomFrog', weight: 5 },
            { id: 'mushroomTeeth', weight: 5 },
            { id: 'mushroomMonster', weight: 13 },
            { id: 'mushroomSoldier', weight: 13 },
            { id: 'mushroomSoldierLucky', weight: 1 },
          ],
        },
      ],
    },
    mountain_pass: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 20,
          items: [
            { id: 'golemBaby', weight: 10 },
            { id: 'woodOctopus', weight: 10 },
            { id: 'golemBoar', weight: 5 },
            { id: 'golemMountain', weight: 5 },
            { id: 'woodRoof', weight: 2 },
          ],
        },
        {
          minLevel: 21,
          maxLevel: 40,
          items: [
            { id: 'golemBaby', weight: 10 },
            { id: 'woodOctopus', weight: 10 },
            { id: 'golemBoar', weight: 5 },
            { id: 'golemMountain', weight: 5 },
            { id: 'woodRoof', weight: 2 },
            { id: 'golemMountainLucky', weight: 1 },
          ],
        },
        {
          minLevel: 41,
          maxLevel: 60,
          items: [
            { id: 'golemBaby', weight: 7 },
            { id: 'woodOctopus', weight: 7 },
            { id: 'golemBoar', weight: 10 },
            { id: 'golemMountain', weight: 10 },
            { id: 'woodRoof', weight: 10 },
            { id: 'golemMountainLucky', weight: 1 },
          ],
        },
        {
          minLevel: 61,
          items: [
            { id: 'golemBaby', weight: 2 },
            { id: 'woodOctopus', weight: 2 },
            { id: 'golemBoar', weight: 5 },
            { id: 'golemMountain', weight: 5 },
            { id: 'woodRoof', weight: 13 },
            { id: 'golemMountainLucky', weight: 1 },
          ],
        },
      ],
    },
    forbidden_city: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 80,
          items: [
            { id: 'robotNo1', weight: 12 },
            { id: 'robotNo2', weight: 12 },
            { id: 'robotNo3', weight: 5 },
            { id: 'robotNo4', weight: 5 },
            { id: 'robotNo5', weight: 2 },
            { id: 'robotNo5Lucky', weight: 1 },
          ],
        },
        {
          minLevel: 81,
          maxLevel: 120,
          items: [
            { id: 'robotNo1', weight: 8 },
            { id: 'robotNo2', weight: 8 },
            { id: 'robotNo3', weight: 5 },
            { id: 'robotNo4', weight: 5 },
            { id: 'robotNo5', weight: 5 },
            { id: 'robotNo5Lucky', weight: 1 },
            { id: 'robotNo7', weight: 5 },
          ],
        },
        {
          minLevel: 121,
          items: [
            { id: 'robotNo1', weight: 5 },
            { id: 'robotNo2', weight: 5 },
            { id: 'robotNo3', weight: 5 },
            { id: 'robotNo4', weight: 5 },
            { id: 'robotNo5', weight: 5 },
            { id: 'robotNo5Lucky', weight: 1 },
            { id: 'robotNo7', weight: 5 },
          ],
        },
      ],
    },
    new_eden: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 1,
          maxLevel: 80,
          items: [
            { id: 'robotNo1', weight: 10 },
            { id: 'robotNo2', weight: 10 },
            { id: 'robotNo3', weight: 6 },
            { id: 'robotNo4', weight: 6 },
            { id: 'robotNo5', weight: 6 },
            { id: 'robotNo5Lucky', weight: 1 },
            { id: 'skeleton', weight: 10 },
            { id: 'skelAssassin', weight: 10 },
            { id: 'darkShaman', weight: 10 },
            { id: 'mushroomSoldier', weight: 10 },
            { id: 'slimeKnight', weight: 10 },
            { id: 'slimeGems', weight: 10 },
            { id: 'skel2Axe', weight: 10 },
            { id: 'skelGreatSword', weight: 10 },
            { id: 'golemMountainLucky', weight: 10 },
            { id: 'slimeBoneLucky', weight: 10 },
            { id: 'mushroomSoldierLucky', weight: 1 },
            { id: 'darkBigGuyLucky', weight: 1 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
        {
          minLevel: 81,
          items: [
            { id: 'robotNo1', weight: 10 },
            { id: 'robotNo2', weight: 10 },
            { id: 'robotNo3', weight: 6 },
            { id: 'robotNo4', weight: 6 },
            { id: 'robotNo5', weight: 20 },
            { id: 'robotNo5Lucky', weight: 1 },
            { id: 'robotNo7', weight: 20 },
            { id: 'skeleton', weight: 10 },
            { id: 'skelAssassin', weight: 10 },
            { id: 'darkShaman', weight: 20 },
            { id: 'mushroomSoldier', weight: 10 },
            { id: 'slimeKnight', weight: 10 },
            { id: 'slimeGems', weight: 10 },
            { id: 'skel2Axe', weight: 20 },
            { id: 'skelGreatSword', weight: 20 },
            { id: 'golemMountainLucky', weight: 10 },
            { id: 'slimeBoneLucky', weight: 1 },
            { id: 'mushroomSoldierLucky', weight: 1 },
            { id: 'darkBigGuyLucky', weight: 1 },
            { id: 'skelGreatSwordLucky', weight: 1 },
          ],
        },
      ],
    },
  },
  $0 = {
    outer_temple: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 6,
          items: [
            { id: 'skelFireHead', weight: 1 },
            { id: 'livingArmor', weight: 3 },
            { id: 'darkDemon', weight: 1 },
            { id: 'woodGolem', weight: 3 },
            { id: 'mushroomLargeBoss', weight: 1 },
          ],
        },
      ],
    },
    seaside_cliffs: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 6,
          items: [
            { id: 'livingArmor', weight: 10 },
            { id: 'skelFireHead', weight: 1 },
            { id: 'darkDemon', weight: 1 },
            { id: 'woodGolem', weight: 1 },
            { id: 'mushroomLargeBoss', weight: 1 },
          ],
        },
      ],
    },
    mossy_forest: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 6,
          items: [
            { id: 'darkDemon', weight: 4 },
            { id: 'mushroomLargeBoss', weight: 1 },
          ],
        },
      ],
    },
    ruined_path: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 6,
          items: [
            { id: 'skelFireHead', weight: 8 },
            { id: 'darkDemon', weight: 1 },
            { id: 'mushroomLargeBoss', weight: 1 },
          ],
        },
      ],
    },
    fields: {
      type: 'oneOf',
      tiers: [{ minLevel: 6, items: [{ id: 'mushroomLargeBoss', weight: 1 }] }],
    },
    mountain_pass: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 6,
          items: [
            { id: 'woodGolem', weight: 18 },
            { id: 'skelFireHead', weight: 2 },
            { id: 'darkDemon', weight: 2 },
            { id: 'mushroomLargeBoss', weight: 2 },
          ],
        },
      ],
    },
    forbidden_city: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 6,
          items: [
            { id: 'skelFireHead', weight: 1 },
            { id: 'livingArmor', weight: 1 },
            { id: 'darkDemon', weight: 1 },
            { id: 'woodGolem', weight: 1 },
            { id: 'robotNo6', weight: 8 },
          ],
        },
      ],
    },
    new_eden: {
      type: 'oneOf',
      tiers: [
        {
          minLevel: 6,
          items: [
            { id: 'skelFireHead', weight: 1 },
            { id: 'skelIceHead', weight: 2 },
            { id: 'robotNo6', weight: 3 },
            { id: 'livingArmor', weight: 1 },
            { id: 'darkDemon', weight: 1 },
            { id: 'woodGolem', weight: 1 },
            { id: 'icyWoodGolem', weight: 2 },
            { id: 'robotBoss', weight: 6 },
          ],
        },
      ],
    },
  }
